src/transfers-history/README.md, src/transfers-history/adapters/db/transfers-repository.ts, src/transfers-history/adapters/web3/SpokePoolEventsQuerier.ts, src/transfers-history/client.e2e.ts, src/transfers-history/client.ts, src/transfers-history/config.ts, src/transfers-history/services/SpokePoolEventsQueryService.ts
This PR fixes a couple of issues identified during testing the FE integration
1. getPendingTransfers() was returning the filled transfers
2. I parallelised the calls for getting FundsDeposited and RelayFilled events
3. I parallelised the queryFilter() calls in case these calls need to be performed in batches (web3 provider limitation)
4. `lowerBoundBlockNumber` optional parameter is now part of the client config object and SHOULD be provided in order to limit the number of the queried blocks
=> fix(transfers-history): improve response times

src/transfers-history/README.md, src/transfers-history/client.e2e.ts, src/transfers-history/client.ts, src/transfers-history/config.ts, src/transfers-history/index.ts
This PR stops events from being triggered if the fetching was stopped. This could happen when the last execution of the `setInterval()` callback was happening after the call of `stopFetchingTransfers()`
Also, the client instantiation requires the providers to be passed, instead of the provider URLs. This way we'll have less providers in our app
=> fix: prevent events from being triggered after fetching was stopped 

src/transfers-history/adapters/db/transfers-repository.ts, src/transfers-history/adapters/web3/SpokePoolEventsQuerier.ts, src/transfers-history/client.e2e.ts, src/transfers-history/client.ts, src/transfers-history/services/SpokePoolEventsQueryService.ts
Signed-off-by: amateima <amatei@umaproject.org>
This PR fixes a small issue I found. In some cases the RelayFilled events were inserted into the database before the initial deposit event, leading to data inconsistencies. Now, the filling events are inserted into the store only after all FundsDeposited events from all chains were fetched.
=> fix: fix processing of fill events

src/pool/poolClient.e2e.ts, src/pool/poolClient.ts
This is an issue where if a user with lp tokens sends them to another address, or receives them from another address, the fee calculation becomes completely broken.
This fix will look up transfer events on the erc20 contract, ignore mint/burn transactions, and then lookup exchange rates based on the block that those transfers happen. The total value of these transfers are then added/subtracted from your total deposit value (depending if u received or sent tokens).  To enable this feature, you must specify in the config that you have provided an archive provider, and you must have an archive node.
=> fix: handle fee calcs for lp transfers

src/transfers-history/adapters/db/transfers-repository.ts, src/transfers-history/client.e2e.ts, src/transfers-history/client.ts, src/transfers-history/model/transfer.ts
Signed-off-by: amateima <amatei@umaproject.org>
Quick change in order to get the hashes of the fill transactions for displaying them in Across frontend
=> feat(tx-history): add fill txs to transfers

src/contracts/acrossConfigStore.e2e.ts, src/pool/poolClient.ts
fixes this 
```
react_devtools_backend.js:4026 error loading user TypeError: Cannot read properties of undefined (reading 'tokenBalances')
at gf (poolClient.ts:322:41)
at f.<anonymous> (poolClient.ts:644:7)
at c (runtime.js:63:40)
at Generator._invoke (runtime.js:294:22)
at Generator.next (runtime.js:119:21)
at k (23.a8c21cbc.chunk.js:2:682903)
at i (23.a8c21cbc.chunk.js:2:683106)
at 23.a8c21cbc.chunk.js:2:683165
at new Promise (<anonymous>)
at f.<anonymous> (23.a8c21cbc.chunk.js:2:683046)
```
For some reason this can sometimes be undefined and typescript is not picking that up
=> fix: optional chaining to fix undefined error

src/transfers-history/adapters/db/transfers-repository.ts, src/transfers-history/client.e2e.ts, src/transfers-history/client.ts
Signed-off-by: amateima <amatei@umaproject.org>
This PR improves the TX History client to be able to fetch all Across V2 deposits by calling `client.startFetchingTransfers("all")` instead of a particular ETH address
=> feat: get all txs history

src/lpFeeCalculator/lpFeeCalculator.test.ts, src/lpFeeCalculator/lpFeeCalculator.ts
Note: The [across-v2](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-157.md#finding-slow-relays) UMIP doesn't reflect this truncation language yet but this PR can be merged in before hand since its backwards compatible. The `relayer-v2` code will then just need to pass in a flag to turn on truncation. 
The relayer and dataworker might want to only truncate %'s after a certain quote time so that it can validate older realized LP fee %'s
=> feat: Truncate realized LP fee %'s to match UMIP

src/relayFeeCalculator/chain-queries/arbitrum.ts, src/relayFeeCalculator/chain-queries/boba.ts, src/relayFeeCalculator/chain-queries/optimism.ts
This PR updates the default spokePoolAddress parameters on the Optimism, Boba, and Arbitrum QueryInterface classes. The new addresses align with the [official documentation](https://docs.across.to/v2/developers/contract-addresses).
=> improve: Update default spokepool addresses

src/coingecko/Coingecko.e2e.ts, src/coingecko/Coingecko.ts, src/relayFeeCalculator/chain-queries/arbitrum.ts, src/relayFeeCalculator/chain-queries/boba.ts, src/relayFeeCalculator/chain-queries/ethereum.ts, src/relayFeeCalculator/chain-queries/optimism.ts, src/relayFeeCalculator/chain-queries/polygon.ts, src/relayFeeCalculator/chain-queries/queries.e2e.ts, src/relayFeeCalculator/relayFeeCalculator.test.ts, src/relayFeeCalculator/relayFeeCalculator.ts
This will allow Vercel API for example to precompute Coingecko price and pass into SDK so that SDK doesn't have to make API call
=> feat: Allow relayer fee user to pass in token price to use

src/coingecko/Coingecko.ts, src/relayFeeCalculator/chain-queries/arbitrum.ts, src/relayFeeCalculator/chain-queries/boba.ts, src/relayFeeCalculator/chain-queries/ethereum.ts, src/relayFeeCalculator/chain-queries/optimism.ts, src/relayFeeCalculator/chain-queries/polygon.ts, src/relayFeeCalculator/chain-queries/queries.e2e.ts, src/relayFeeCalculator/relayFeeCalculator.ts
Clients can pass in any loggers they want as long as they conform to the interface. This can work well with loggers such as winston and GCP logger.
=> improve: Allow clients to pass in an optional custom logger

package.json, src/coingecko/Coingecko.e2e.ts, src/coingecko/Coingecko.ts, src/utils.ts
We want to reduce coingecko Pro API requests to under 500,000/month, currently we're on track for 1.2million a month.
Some stats:
- A direct request to CG basic API takes 200ms if successful or 100ms if you get rate limited and receive a 429
- Same with CG pro API: Takes 200ms if successful
- CG API needs to warm up, first call always takes slightly longer (say 250-300ms instead of 150-200)
Coingecko API requests can only be sent on cache misses, which should be rare (5% of requests) [following this PR](https://github.com/across-protocol/frontend-v2/commit/995853ea370c29b495a799848ca444412d9e53a4). For cache misses, the response time is already going to be slow because of how the Lambda function works, so saving 100ms on these requests isn't a material improvement.
Therefore, the extra …
=> improve(Coingecko): Use PRO API as fallback, not first choice

package.json
Version in package.json always needs to be changed first before creating any new release/tag
=> chore: Bump version to 0.1.21 as 0.1.20 was accidentally created without changing package.json

src/coingecko/Coingecko.ts
By wrapping getContractPrices(), we save ~24kB in response size (~99%).
From limited testing on my end, there's also a minor latency saving of
~100mS per request. Your mileage will inevitably vary.
Ref: ACX-194
=> improve(Coingecko): Faster token price retrievals

src/transfers-history/adapters/db/transfers-repository.ts, src/transfers-history/adapters/web3/SpokePoolEventsQuerier.ts, src/transfers-history/client.e2e.ts, src/transfers-history/client.ts, src/transfers-history/model/transfer.ts, src/transfers-history/services/SpokePoolEventsQueryService.ts
This PR extends the `Transfer` entity by adding speed-up / relay fee-related fields to the model and the respective handlers. The goal of this addition is to display fees in the transactions table of the UI and allow handling of speed-ups in the UI.
=> feat: handling of `RequestedSpeedUpDepositEvent` events

src/coingecko/Coingecko.ts
I think there's a small bug in the Coingecko client whereby we access the usd field, but the base currency could be non usd.
=> fix: getContractPrices can't handle non usd base currencies

src/coingecko/Coingecko.ts
250 => 500 mS, per observation that timeouts are by far the leading cause of Pro lookups.
=> improve(Coingecko): Bump Coingecko timeout

package.json, yarn.lock
Follow up PR to https://github.com/across-protocol/contracts-v2/pull/186
This PR updates some package dependencies which should fix the currently broken `@across-protocol/sdk-v2` package that errors with a `TypeError`:
```
/Users/dh.kim/Projects/across/merkle-distributor/node_modules/@uma/sdk/dist/src/clients/optimisticOracle/client.ts:16
export const contractInterface = new utils.Interface(getV1OptimisticOracleInterfaceAbi());
^
TypeError: rateModelStore.getV1OptimisticOracleInterfaceAbi is not a function
at Object.<anonymous> (/Users/dh.kim/Projects/across/merkle-distributor/node_modules/@uma/sdk/dist/src/clients/optimisticOracle/client.ts:16:54)
at Module._compile (node:internal/modules/cjs/loader:1105:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
at …
```
=> chore: update deps and bump v0.1.28

package.json
Includes the new gasPriceOracle and priceClient implementations.
I'd like to get this approved now, but will hold off on merging it until the priceClient is in.
=> chore: Bump version to 0.1.29

src/gasPriceOracle/oracle.e2e.ts, src/gasPriceOracle/oracle.ts
The existing use of maxFeePerGas gives a pessimistic view on the probable gas cost of the next transaction.
=> fix(gasPriceOracle): Revert to gasPrice for EIP-1559 chains

.github/workflows/lint.yml, .github/workflows/test.yml
[Node LTS version](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#2022-10-25-version-18120-hydrogen-lts-ruyadorno-and-rafaelgss) changed recently, and some packages still using old LTS. Version is now fixed on code. 
=> Fix: CI Node version

src/gasPriceOracle/oracle.e2e.ts
Evaldo's latest PR ratcheted up the CI quality demands, and my code was found wanting... This is
currently a blocking issue for any other PRs going into this repo, since it's blocking CI.
This change eases some of the type mangling that occurs in the oracle.e2e test, such that the linter and transpiler are a little less offended by it.
=> fix(gasPriceOracle): Fix tests

package.json, src/contracts/hubPool.ts, src/utils.ts
https://github.com/across-protocol/sdk-v2/commit/7abcbfa7b4690e9706bd6ae91ae66de041427906
correctly divided by 1e18 after toBNWei-ing the gasMultiplier but forgot to add the same division for the Optimism special case
=> fix(relay-fee-calculator): Divide by 1e18 for Optimism gas cost 

src/priceClient/adapters/acrossApi.ts, src/priceClient/adapters/coingecko.ts, src/priceClient/priceClient.e2e.ts
Per this comment to the use of PriceClient in the relayer-v2 repo: https://github.com/across-protocol/relayer-v2/pull/334#discussion_r1003809539.
This reduces some redundancy and makes it easier to instantiate a PriceFeed
instance. Also, name is now an optional argument that can be supplied as part
of the args object; if not supplied then a sensible per-feed default will be used.
=> improve(PriceClient): Simplify PriceFeed constructor arguments

package.json, src/utils.ts
when utilized reserves is < 0, apr's can get so small they toString() into scientific notation
=> fix: Fix APR and APY's to 18 precision

src/priceClient/adapters/coingecko.ts, src/priceClient/adapters/defiLlama.ts, src/priceClient/priceClient.e2e.ts, src/priceClient/priceClient.ts
This change restores the PriceClient's ability to fall back to alternative
price feeds in the event of a price resolution failure.
The PriceClient currently requires each PriceFeedAdapter instance to return
a complete response to any price lookup. This effectively renders CoinGecko
unusable as a price source now that the ACX token is included in price
lookups.
This change modifies the PriceClient such that it will accept an incomplete
response, thereby restoring most of the fallback capability. A price lookup
failure against ACX alone will still cause an exception to be thrown, because
there are no other fallback sources. Some additional thought could be
directed at how to make that more robust in future.
=> feat(PriceClient): Accept partial price responses

package.json, src/lpFeeCalculator/lpFeeCalculator.test.ts, src/lpFeeCalculator/lpFeeCalculator.ts
New issue discovered when using rate model with UBAR=0
=> fix(lpFeeCalculator): Handle divide by 0

package.json, src/relayFeeCalculator/relayFeeCalculator.test.ts, src/relayFeeCalculator/relayFeeCalculator.ts, src/utils.ts
- API computes `maxGasFeePercent` and `minDeposit` in order to compute the minimum deposit for the /limits endpoint, we should standardize this and move the computation to the SDK-v2
- Fixes a divide-by-0 bug where we don't handle the `maxGasFeePercent = 0` case, arising when `feeLimitPercent` is set too low or `capitalFeePercent` is too high
- Returns `maxGasFeePercent` and `minDeposit` which can be used by the FE instead of recomputing [here](https://github.com/across-protocol/frontend-v2/blob/1c531768b36d77119dee9ce4a041f20729bb82ba/api/limits.ts#L197)
=> improve(relayFeeCalculator): Standardize isAmountTooLow with Vercel API's minDeposit calculation

yarn.lock
Initial motivation: https://github.com/microsoft/TypeScript/issues/50583.
Changes:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-9.html
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-8.html
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html
Something that caught my eye is [auto-accessors](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-9.html#a-nameauto-accessors-in-classes-auto-accessors-in-classes) (added in 4.9). I will look forward to using that, at least.
=> chore: Bump ts 4.6.2 -> 4.9.5

src/priceClient/adapters/acrossApi.ts, src/priceClient/adapters/baseAdapter.ts, src/priceClient/adapters/coingecko.ts, src/priceClient/adapters/defiLlama.ts, src/priceClient/priceClient.e2e.ts, src/priceClient/priceClient.ts, yarn.lock
=> improve(PriceClient): Permit retry on failed lookups

src/interfaces/SpokePool.ts, src/interfaces/UBA.ts, src/interfaces/index.ts
This change simply establishes some basic types to be used as part of the UBA ecosystem. Note that the Outflow type is incomplete because it depends on the RefundRequested event, which hasn't been merged yet.
=> chore(across-v2): Add basic UBA types

package.json, src/interfaces/TypedData.ts, src/interfaces/index.ts, src/utils.ts
This is part of ACX-643. Adding this to the SDK makes sense to me in case other projects/components than our FE needs to speed up deposits.
=> feat: update deposit typed data utility

package.json, yarn.lock
Bumping this fixes my local issues with `yarn link`. It makes sense, given the release notes
between v2.0.1 and v2.0.2, but I don't understand why the issue only arises for me when I
link to a local version.
=> chore: Bump contracts-v2 2.0.1 -> 2.0.2

package.json, src/interfaces/UBA.test.ts, src/interfaces/UBA.ts
The existing predicates didn't quite work as expected because the
depositId field exists on all of the UbaFlow union types. This change
changes the isUbaInflow() predicate to look at the deposit-exclusive
quoteTimestamp field, and adds some additional predicates to support
sub-classifying a UbaOutflow. While here, add some tests.
=> fix(UBA): Tweak predicates and add test

src/interfaces/SpokePool.ts
This helps to keep DepositWithBlock aligned with the commonly used tools that work on SortableEvent types.
=> DepositWithBlock.originBlockNumber -> quoteBlockNumber

package.json
0.4.7 includes a broken test, but this didn't prevent it from being packaged and pushed to npm.
Bumping to 0.4.8 is now necessary to get the fixed version to npm.
=> chore(package): Bump version -> 0.4.8

src/interfaces/UBA.ts
isSlowRelay was an unfortunate choice, because it gets relocated as part of the new SpokePool migration. Instead, use repaymentChainId because it's unique to a fill and is not impacted by the new ABI.
=> chore(UBA): Tweak outflowIsFill predicate

src/UBAFeeCalculator/UBAFeeUtility.ts, src/constants.ts, src/contracts/acrossConfigStore.ts, src/contracts/hubPool.ts, src/interfaces/Common.ts, src/interfaces/SpokePool.ts, src/merkleDistributor/MerkleDistributor.ts, src/pool/poolClient.ts, src/relayFeeCalculator/chain-queries/baseQuery.ts, src/relayFeeCalculator/chain-queries/optimism.ts, src/transfers-history/adapters/web3/SpokePoolEventsQuerier.ts, src/transfers-history/client.ts, src/transfers-history/services/SpokePoolEventsQueryService.ts, src/typechain.ts, src/utils.ts
The latest stable version 0.5.3 of the SDK fails to compile on the FE or in a browser environment with 
```
Failed to compile.
./node_modules/@across-protocol/sdk-v2/node_modules/@uma/common/dist/HardhatConfig.js
Cannot find module: 'hardhat-tracer'. Make sure this package is installed.
You can install this package by running: yarn add hardhat-tracer.
```
Or
```
Creating an optimized production build...
Failed to compile.
./node_modules/@across-protocol/contracts-v2/node_modules/hardhat/internal/util/fs-utils.js
Cannot find module: 'fs/promises'. Make sure this package is installed.
You can install this package by running: yarn add fs/promises.
```
AFAICT this is due to browser-incompatible packages (e.g. `@uma/common`, `@across-protocol/contracts-v2@^2.2.0`) that are not optimized for …
=> fix: browser env bundle

package.json, yarn.lock
Aligns with current relayer-v2. nb. This is predicated on https://github.com/across-protocol/sdk-v2/pull/202 being resolved.
=> chore: Bump typescript ^4.6.2 => ^5.0.4

package.json, src/clients/index.ts
This change exports the SpokePool Client in the SDK-V2.
=> fix: export spoke pool client

src/clients/HubPoolClient.ts
Also, set latestBlockNumber in the constructor. If no deploymentBlock is supplied, default to 0.
Once this is pulled into relayer-v2, we can make some follow-on adjustments there and then redefine latestBlockNumber as a number only, so callers don't need to consider the `undefined` scenario.
Fixes ACX-1048
=> improve(HubPoolClient): Track deploymentBlock

src/interfaces/HubPool.ts
This is needed so that tests defined in the relayer-v2 repository can import this type and use it in tests.
=> chore(UBA): Define HubPool TokenRunningBalance type

package.json, src/transfers-history/adapters/web3/SpokePoolEventsQuerier.ts, src/typechain.ts, yarn.lock
This PR bumps the `@across-protocol/contracts-v2` version to the latest version. To accomplish this, several typechain imports needed to be made. 
Three scripts have been added to let the package.json version be upgraded in a more convenient manner.
=> chore: bump contracts version

src/utils/TypeGuards.ts, src/utils/index.ts
Can reasonably foresee a need for these in the sdk-v2 repository, given some of the migrations that are occurring. Will subsequently update the relayer-v2 repository to import these after bumping the SDK version.
Copied from https://github.com/across-protocol/relayer-v2/blob/master/src/utils/TypeGuards.ts
=> refactor(utils): Migrate relayer-v2 typeguards

src/clients/AcrossConfigStoreClient.ts, src/clients/HubPoolClient.ts, src/clients/SpokePoolClient.ts
The HubPoolClient will need to read from the ConfigStoreClient, and so far there don't seem to be any hard reasons for why the ConfigStoreClient needs a HubPoolClient instance. Therefore, migrate the necessary parts of the ConfigStoreClient to the HubPoolClient, and supply the HubPoolClient with a ConfigStoreClient during instantiation.
=> refactor(HubPoolClient): Reverse ConfigStoreClient dependencies

src/clients/AcrossConfigStoreClient.ts, src/clients/mocks/MockConfigStoreClient.ts, src/clients/mocks/MockEvents.ts
This change provides an option to override ConfigStoreClient on-chain queries
via _update(). The pattern is pretty consistent with what we have in the
HubPoolClient and SpokePoolClient. For the MockConfigStoreClient it was
necessary to inherit super._update() by default, for compatibility with existing
uses of the MockConfigStoreClient in relayer-v2 tests. Ultimately it would be
nice to remove that.
Addtionally, support mocked getBlock() for HubPoolClient test. This is needed
for the pending runningBalances UBA update.
=> improve: Split ConfigStoreClient update()

src/clients/HubPoolClient.ts, src/clients/SpokePoolClient.ts
The self-dispute on the weekend may be traceable to the fact that we don't specify the blockTag on some queries in the update() methods.
Fixes ACX-1172
=> improve: Better robustness in client update methods

src/interfaces/Error.ts
This borrows from ethers v6, where the EthersError type is defined as having an optional error member. v5 typically does the same thing, by nesting errors, though without explicitly defining the EthersError type.
Sourced from (as at 026c5bb13724756f8ae5c64a0692789c1e27361c):
https://github.com/ethers-io/ethers.js/blob/main/src.ts/utils/errors.ts#L156
=> improve(Error): Support nested Ethers Errors

src/clients/AcrossConfigStoreClient.ts
Allow the applicable version to be searched by block number. This is useful for the pending UBA version bump. Additionally, build the array of cumulative version updates in descending order, so that it doesn't have to be re-ordered on each use.
=> improve(ConfigStoreClient): Additional version helper

src/clients/UBAClient.ts, src/clients/index.ts
Imported almost as-is from relayer-v2, with only the minimum modifications
necessary to align with the slightly more strict ts requirements over here. There
are some todos remaining to be resolved from that - notably some stubborn
type assertions that should be smoothed out post-import.
=> feat(UBA): Import UBAClient from relayer-v2

src/clients/SpokePoolClient.ts
The SpokePool "numberOfDeposits" state variable is the depositId of the _next_
deposit to be confirmed; not the last one.
I'm not aware of any cases where this has caused an error, but the bots sometimes
log that they can't find a specific deposit during periods of RPC instability. Fixing
this allows us to rule it out as a potential error source.
=> fix: Remove off-by-one error in SpokePoolClient

src/clients/mocks/MockSpokePoolClient.ts
The SpokePoolClient tries to resolve the destinationToken against the set of known tokens in the HubPoolClient, so it's important to propagate the value supplied by the caller. If no value has been supplied, sub in the ZERO_ADDRESS, because this is what the SpokePoolClient resolves when it has no reference for the HubPoolClient.
In the mean time, there are workarounds in some relayer-v2 tests to plaster over the issue. They will be fixed once this change migrates back to relayer-v2 via an sdk-v2 bump.
=> fix(mock): Don't override generated fill destinationToken

package.json, src/gasPriceOracle/adapters/index.ts, src/gasPriceOracle/oracle.e2e.ts, src/gasPriceOracle/oracle.ts
Ethers hardcodes a price of 1.5 Gwei for the priority fee. On Arbitrum, the priority fee is refunded to the caller, so it doesn't makse sense to use that in gas computations since it results in over-estimation.
=> fix: Revert to legacy gas pricing for Arbitrum

src/clients/UBAClient/index.ts
Necessary for external users now that the UBAClient exposes public methods that require this type as an input.
Note: I exported this directly from the UBAClient directory because the user of the UBAClient should be able to import everything it needs from that directory. But we might want to do a little re-org to make sure that the type itself is defined in the right place. @james-a-morris I assume you'll have an idea about how to do it nicely.
=> chore(UBA): Export UBA fee calculator types

src/clients/UBAClient/UBAClientAbstract.ts, src/clients/UBAClient/UBAClientWithRefresh.ts
refundChainId -> destinationChainId for LP fee computations.
=> chore(UBAClient): Adjust variable names after previous change

package.json, src/clients/mocks/MockEvents.ts, src/clients/mocks/MockHubPoolClient.ts, src/clients/mocks/MockSpokePoolClient.ts, src/utils/common.ts
Unfortunately, the import path `@across-protocol/contracts-v2/dist/test-utils` also breaks the frontend. Because we import only a simple utility from there, I copy-pasted it to the local utils file.
=> fix: remove contracts-v2 test utils dep

package.json
Bumps the SDK minor version number to include changes made to the UBA fee calculations
=> chore: bump sdk

package.json, src/clients/UBAClient/UBAClientWithRefresh.ts
This change adds additional logic to the UBAClient's update function. The UBA function now updates the underlying hubpool/config store/spoke pools only if `forceRefresh` is passed and/or an update has not yet been called on any sub client.
=> improve: add optional refresh to UBAClient update function

package.json, src/clients/SpokePoolClient.ts
This change includes valid JSDoc comments for all the functions within the SpokePool Client.
As the relayer clients are now within the SDK, it may be effective to provide proper doc comments at all levels for developers to use / better understand the gist of the code.
=> docs(UBA): :memo: include JSDocs for spoke client

package.json, src/clients/SpokePoolClient.ts, src/interfaces/SpokePool.ts, src/interfaces/UBA.test.ts, src/interfaces/UBA.ts
The chain ID of the SpokePool where the RefundRequest event was emitted is not part of the event itself, so append it here. This is useful for filtering further up in the stack.
=> improve(SpokePoolClient): Add repaymentChainId to RefundRequest objects

src/clients/UBAClient/UBAClientBase.ts, src/clients/UBAClient/UBAClientUtilities.ts, src/utils/index.ts
Refund Request validation has been wrong since it was first added, because it relied on the deposits having previously been validated, and that wasn't the case. It also needs to be async because it must be able to search for old fills and deposits via an RPC provider.
While here, remove refundRequestIsValid() from UBAClientBase because it's unlikely to be used in its current form, and refund request validation belongs between the UBAClient and SpokePoolClients.
=> fix(UBA): Fix RefundRequest validation

src/clients/AcrossConfigStoreClient.ts, src/clients/BaseAbstractClient.ts, src/clients/HubPoolClient.ts, src/clients/SpokePoolClient.ts, src/clients/UBAClient/UBAClientBase.ts, src/clients/UBAClient/UBAClientUtilities.ts, src/clients/UBAClient/UBAClientWithRefresh.ts
This PR essentially adds a base-client that is extended by all of our bot clients. The reason being: we have common `isUpdated` logic in all clients and that should be strictly enforced.
=> feat: add base-client extension to all clients

src/clients/UBAClient/UBAClientUtilities.ts
These helpers interface to individual SpokePoolClient instances and handle the necessary filtering and validation on behalf of the caller. They should ultimately be migrated into a dedidated SpokePoolManager class, alongside some other select utilities in the UBAClientUtilities file.
=> improve: Add general getFills() and getRefundRequest() helpers

package.json, src/clients/HubPoolClient.ts, src/clients/mocks/MockConfigStoreClient.ts, src/clients/mocks/MockEvents.ts, src/clients/mocks/MockHubPoolClient.ts, src/clients/mocks/MockSpokePoolClient.ts
This change migrates to the use of a singleton for event managers, enabling multiple "client" classes to see consistent block number increments. This addresses a race condition in the relayer-v2 runningBalances test where the ConfigStoreClient and HubPoolClient can get out of sync and disagree about the applicable version.
While here, add an additional check to ensure that FundsDeposited events are generated with sequential (or at least incrementing) depositIds.
=> improve(test): Singleton event manager in mocked clients

src/UBAFeeCalculator/UBAFeeSpokeCalculator.ts, src/UBAFeeCalculator/UBAFeeSpokeCalculatorAnalog.ts, src/clients/UBAClient/UBAClientBase.ts, src/clients/UBAClient/UBAClientUtilities.ts, src/interfaces/UBA.ts
- We need to make sure we're only passing the snapshotted running balances back and forth between `getEventFee` and `calculateHistoricalRunningBalance`
- Add clarifying comments as to the usage of these functions
=> fix(UBAFeeCalculator): Refine `calculateHistoricalRunningBalance`

src/clients/UBAClient/UBAClientUtilities.ts, src/clients/UBAClient/UBAClientWithRefresh.ts, src/relayFeeCalculator/relayFeeCalculator.ts
While working on the `GET /uba-bundle-state` endpoint for the quote engine, I noticed that we pass the wrong (?) queries here https://github.com/across-protocol/sdk-v2/blob/use-correct-queries-relay-fee-calculator/src/clients/UBAClient/UBAClientUtilities.ts#L351. The old `RelayFeeCalculatorConfig` expects as a property an instance of `QueryInterface` which implements the respective `gasCosts`, `price`, `decimals` queries for a single chain. But AFAICT we need the queries of the respective destination chain.
This PR tries to fix this by allowing to instantiate an instance of `RelayerFeeCalculator` using a `queriesMap` and an additional `destinationChainId` parameter. I chose this approach in order to not break other code that uses the calculator.
=> feat: allow passing `queriesMap` to relay fee calc config

src/UBAFeeCalculator/UBAFeeSpokeCalculatorAnalog.ts
If we are over the target, subtract the difference from the net running balance adjustment so that the dataworker can instruct the spoke pool to return funds to the hub pool.
If we are under the target, add the difference to the net running balance adjustment so that the dataworker can instruct the hub pool to send funds to the spokepool.
=> fix: Subtract netRunningBalanceAdjustment when over target

src/UBAFeeCalculator/UBAFeeCalculator.test.ts, src/UBAFeeCalculator/UBAFeeConfig.ts, src/UBAFeeCalculator/UBAFeeSpokeCalculator.ts, src/UBAFeeCalculator/UBAFeeSpokeCalculatorAnalog.ts, src/UBAFeeCalculator/UBAFeeTypes.ts, src/UBAFeeCalculator/index.ts, src/clients/UBAClient/UBAClientTypes.ts, src/clients/UBAClient/UBAClientUtilities.ts
- `UBAFeeConfig` makes caller set a default for `balanceTriggerThreshold`, so that calling `getBalanceTriggerThreshold` never returns `undefined`.
- `UBAFeeSpokeCalculatorAnalog` can now assume that the lower/upper bound thresholds are always defined. If they are 0, ignore them.
- Makes all class variables `protected` rather than `private` so that a `MockUBAFeeConfig` can be built easier. When these variables are `private`, then the mock class needs to redefine them which is tedious
- Export types from `UBAFeeConfig` out of `UBAFeeTypes`
=> improve(UBAFeeConfig): Add possibility for user to set a default for `balanceTriggerThreshold`

src/clients/HubPoolClient.ts
The Vercel API handler only can pass providers
=> fix: use provider instead of signer for fetch token

package.json, src/UBAFeeCalculator/UBAFeeConfig.ts, src/UBAFeeCalculator/UBAFeeUtility.ts, src/apiClient/mockedClient.ts, src/clients/AcrossConfigStoreClient/AcrossConfigStoreClient.ts, src/clients/HubPoolClient.ts, src/clients/SpokePoolClient.ts, src/clients/UBAClient/UBAClientBase.ts, src/clients/UBAClient/UBAClientTypes.ts, src/clients/UBAClient/UBAClientUtilities.ts, src/clients/UBAClient/UBAClientWithRefresh.ts, src/clients/mocks/MockHubPoolClient.ts, src/constants.ts, src/gasPriceOracle/adapters/arbitrum.ts, src/gasPriceOracle/adapters/ethereum.ts, src/interfaces/SpokePool.ts, src/interfaces/UBA.ts, src/pool/poolClient.ts, src/transfers-history/client.ts, src/utils/BundleUtils.ts, src/utils/FlowUtils.ts, src/utils/index.ts
This PR overall tries to make `updateUBAClients` re-use existing functions that have been battle tested in production code.
- `updateUBAClient`'s first step is to construct bundle block ranges for a specified number of the most recently validated bundles. The first fix refactors the block range construction logic into a function `getMostRecentBundles` which has unit tests accompanying it [here](https://github.com/across-protocol/relayer-v2/pull/815/files).
- `calculateUtilizationBoundaries` doesn't correctly take into account both the `refundChain` AND the `originChain` when computing utilization. The UMIP states that utilization calculation should take into account flows being added to the ETH spoke pool from a deposit and subtracted when ETH is the destination spoke pool.
- …
=> fix(UBAClient): Add various fixes to updateUBAClients

src/UBAFeeCalculator/UBAFeeConfig.ts, src/clients/AcrossConfigStoreClient/AcrossConfigStoreClient.ts, src/clients/UBAClient/UBAClientUtilities.ts, src/clients/UBAClient/UBAClientWithRefresh.ts, src/utils/JSONUtils.ts
Some things I had to add and fix in order to get it working in the Vercel API handler:
- handle `undefined` of var `threshold` 
- utility function to deserialize the uba client state
- because we return the state as JSON when consuming it in the `/suggested-fees` handler, we need to parse it (especially `BigNumber` instances and `UBAFeeConfig` instance)
- some fixes in the `UBAClientWithRefresh.update` method (not 100% if I am correct here though)
=> fix: uba client fixes for quote engine

src/clients/AcrossConfigStoreClient/AcrossConfigStoreClient.ts, src/clients/HubPoolClient.ts, src/clients/SpokePoolClient.ts, src/clients/UBAClient/UBAClientUtilities.ts
In the UBA model, events should be matched to UBA config based on the bundle start block containing the event, rather than the event.quoteBlock
=> feat: match events with correct UBA config based on bundle start block not quote block

package.json, src/clients/SpokePoolClient.ts, src/clients/UBAClient/UBAClientBase.ts, src/clients/UBAClient/UBAClientUtilities.ts, src/clients/UBAClient/UBAClientWithRefresh.ts, src/interfaces/UBA.ts, src/utils/FlowUtils.ts
- `computeLpFee` shouldn't try to retrieve a bundle config from state since its expected to be used by the relayer. If the relayer is trying to set the LP fee for a very recent deposit, then it should not be using the config included at the time of the last validated bundle, instead it should be using the latest config in the `ConfigStore` contract
- `getModifiedFlows` is refactored and now is used in `resolveHistoricalDepositForFill` to reduce the DOS vector
- The only remaining DOS vector is looking up an old fill for a refund. I've left a TODO
Fixes #ACX1321
=> feat: Relocate computeSystemFee and refactor getModifiedFlows

src/clients/AcrossConfigStoreClient/AcrossConfigStoreClient.ts, src/clients/HubPoolClient.ts, src/clients/SpokePoolClient.ts, src/interfaces/ConfigStore.ts, src/interfaces/HubPool.ts, src/interfaces/SpokePool.ts
In an effort to make the states of `ConfigStoreClient`, `HubPoolClient` and `SpokePoolClient` serializable, i.e. cachable, I added custom `toJSON` methods. The `updateFromJSON` method allows updating the client state from the output of `toJSON`.
I added these because the performances of the `uba-client-state` job and serverless handler of `/suggested-fees` can be increased significantly by utilizing the above methods and caching.
For example, in the `/suggested-fees` handler, we can use cached `HubPoolClient` and `ConfigStoreClient` states in addition to the already cached `UBAClientState`. This way we don't need to call the `update()` methods to save time.
=> feat(clients): add `toJSON` and `updateFromJSON` methods

package.json, src/clients/SpokePoolClient.ts, src/clients/UBAClient/UBAClientWithRefresh.ts, src/clients/mocks/MockEvents.ts, src/clients/mocks/MockSpokePoolClient.ts, src/interfaces/SpokePool.ts, src/interfaces/UBA.test.ts
Add the block timestamp to FundsDeposited, FilledRelay and RefundRequested events. This allows upper layers to perform additional checks based on cross-chain timestamps.
This change is plucked from @nicholaspai's existing draft PR here: https://github.com/across-protocol/sdk-v2/pull/332/files#diff-8aaa64629d1940a0ea618d935e9d93044f09df5bd32d7352ee02c415a763d250
This change is also implicitly dependent on the following change in relayer-v2, because without it the relayer will experience a potentially significant performance decrease (and a potentially large increase in RPC usage): https://github.com/across-protocol/relayer-v2/pull/835
ACX-1328
=> improve: Append block timestamp to SpokePool events

package.json, src/caching/IPFS/PinataIPFSClient.ts, src/caching/IPFS/index.ts, src/caching/IPFSClient.ts, src/caching/index.ts, src/index.ts, src/interfaces/CachingMechanism.ts, src/utils/IPFSUtils.ts, src/utils/JSONUtils.ts, src/utils/LogUtils.ts, src/utils/index.ts, yarn.lock
This PR adds an IPFS client to the SDK. Additionally, this client complies with the `CachingMechanism` interface so that we can use it in arbitrary locations throughout the SDK where caching is concerned.
=> feat: add IPFS caching client

package.json, src/clients/AcrossConfigStoreClient/AcrossConfigStoreClient.ts, src/clients/HubPoolClient.ts, src/clients/UBAClient/UBAClientUtilities.ts, src/clients/UBAClient/UBAClientWithRefresh.ts, src/clients/mocks/MockConfigStoreClient.ts, src/interfaces/ConfigStore.ts, src/utils/BundleUtils.ts
Adds indices scraping to the across config store. This change is aimed at providing a dynamic approach to determining the across chain indices across block ranges.
<details><summary>Details</summary>
<p>
[feat: ✨ add global chain index scraping from configstore](https://github.com/across-protocol/sdk-v2/commit/6cbe2c82ddc3448a8844fd77cc3e0521795d4204) 
This change adds global config store updates for the chain ID list. If the user requests chain indices prior to the relayer's knowledge then it will return the hardcoded value per the UMIP
[feat: ✨ add generic to global config updates](https://github.com/across-protocol/sdk-v2/commit/e5d67a929732891a67c41fb42bc563484515982e) 
This change adds generic value types for global config updates. Currently, value updates were only able to be …
=> feat: ✨ add global chain index scraping from configstore 

src/clients/AcrossConfigStoreClient/AcrossConfigStoreClient.ts
The UBA config is large and logging this parsed config for every token is very noisy
=> improve(ConfigStoreClient): Remove noisy log

src/gasPriceOracle/oracle.e2e.ts, src/gasPriceOracle/oracle.ts
This change explicitly signals that zkSync gas price estimates should be based on the legacy method, rather than eip1559.
The zkSync docs indicate that type 2 (EIP1559) transactions are supported, but clarify that the maxFee* parameters are ignored:
https://era.zksync.io/docs/reference/concepts/transactions.html#eip-1559-0x2
The zkSync-specific provider references the ethers getGasPrice() method, rather than the more post-1559 getFeeData() method that supports the priority fee:
https://era.zksync.io/docs/api/js/providers.html#getgasprice
L2s like zkSync and Optimism are additionally indicating more dynamic pricing based on the corresponding L1 cost of the transaction, and this requires fee estimation based on the actual transaction request. Ultimately we may need to support a strategy …
=> improve(gasPriceOracle): Initial zkSync support

package.json, src/clients/HubPoolClient.ts, src/clients/UBAClient/UBAClientUtilities.ts, src/clients/UBAClient/UBAClientWithRefresh.ts, src/utils/BundleUtils.ts
There is a very important difference between calling `getEnabledChains` and `getChainIdIndices` on the `ConfigStoreClient`. The latter is used to index block numbers to chains while the former is used much more seldomly to limit which chains we care about for whatever operation.
This PR fixes critical bugs in the various clients that create block ranges. I discovered this bug while integration testing the dataworker and UBA client
=> fix: Pass in chainIdIndices instead of enabledChainIds

src/clients/AcrossConfigStoreClient/AcrossConfigStoreClient.ts, src/clients/BaseAbstractClient.ts, src/clients/HubPoolClient.ts, src/clients/SpokePoolClient.ts, src/clients/UBAClient/UBAClientWithRefresh.ts, src/utils/ClientUtils.ts, src/utils/index.ts
In order to find the list of enabled chains from the config store, we need to ensure that the config store has been updated. This is something that should be provided prior to the config store being passed into the constructor of the UBAClient.
Breaking Changes: Any code with the assumption that an unupdated config store can be passed into the UBAClientWithRefresh
=> fix(UBA): :bug: assert that config store is updated

package.json, src/clients/UBAClient/UBAClientConfig.ts, src/clients/UBAClient/UBAClientUtilities.ts, src/clients/UBAClient/UBAClientWithRefresh.ts, src/clients/UBAClient/index.ts
- UBAConfig provides a single config to start that allows caller to customize their dependency on the cache 
- Adds a comment about moving a function into the UBAClient to get access to the cache
- Skips loading bundles from the cache if its earlier than a configured start block
Signed-off-by: nicholaspai <npai.nyc@gmail.com>
=> improve(UBAClient): Add UBAConfig and additional comments + logs

src/clients/AcrossConfigStoreClient/AcrossConfigStoreClient.ts, src/clients/mocks/MockConfigStoreClient.ts
This makes the ConfigStoreClient more compatible with testnet deployments, and helps to ignore obviously incorrect GlobalConfig updates impacting the chain ID indices array.
=> improve(ConfigStoreClient): Add Chain ID awareness

package.json, src/relayFeeCalculator/chain-queries/arbitrum.ts, src/relayFeeCalculator/chain-queries/ethereum.ts, src/relayFeeCalculator/chain-queries/optimism.ts, src/relayFeeCalculator/chain-queries/polygon.ts, src/relayFeeCalculator/chain-queries/zksync.ts, src/utils/DeploymentUtils.ts, src/utils/index.ts
The import path
```js
import { getDeployedAddress } from "@across-protocol/contracts-v2";
```
broke the FE because the package is not tree shakable and contains dependencies that are not compatible with a browser env. We fix this by importing the `getDeployedAddress` directly from the source file.
=> fix(queries): browser compatibility + use chain id enum

package.json, src/gasPriceOracle/oracle.e2e.ts, src/gasPriceOracle/oracle.ts, src/relayFeeCalculator/chain-queries/base.ts, src/relayFeeCalculator/chain-queries/index.ts, src/utils/NetworkUtils.ts
This adds basic base support. This will require a release of contracts-v2 after base constants are included for the Queries object to work.
Is there anything missing from this PR that should be done to support Base?
=> feat: add base support

src/gasPriceOracle/oracle.e2e.ts, src/gasPriceOracle/oracle.ts
One thing to note: as with Optimism, the priority fee should probably be
scaled down aggressively by the caller since ethers hardcodes it to 1.5
Gwei.
=> chore(gasPriceOracle): Basic support for Base

package.json, src/clients/SpokePoolClient.ts, src/clients/UBAClient/UBAClientUtilities.ts, src/constants.ts, src/relayFeeCalculator/relayFeeCalculator.ts, src/utils/BlockExplorerUtils.ts, src/utils/FormattingUtils.ts, src/utils/common.test.ts, src/utils/common.ts, src/utils/index.ts
Correct etherscan link template for Base. Currently, without the trailing `/` after the URL then our assumptions break for logging. Also, `mainnet.basescan.org` is now defunct replaced by just `basescan.org`
This PR now also includes a refactoring to bring `./formattingUtils` from the relayer into the SDK.
=> fix: correct etherscan link & refactoring

src/constants.ts, src/utils/BigNumberUtils.ts
Using these can deliver a small benefit over spinning up new BNs for common numbers like 0 and 1.
=> improve: Export useful ethers constants

package.json, src/utils/FormattingUtils.ts, yarn.lock
This PR carries over the `createFormatFunction` from `@uma/common` into the `@across-protocol/sdk-v2` directly.
=> feat: carry in `createFormatFunction`

package.json, src/clients/BaseAbstractClient.ts, src/clients/HubPoolClient.ts, src/constants.ts, src/interfaces/CachingMechanism.ts, src/utils/CachingUtils.ts, src/utils/LogUtils.ts, src/utils/index.ts
This PR re-introduces the hub pool caching mechanism for storing utilization data in an external cache (i.e. redis). A subsequent PR will need to be introduced in relayer-v2 to make use of this functionality. Otherwise, it is completely pass through in the current state.
This functionality relies on the agnostic caching interface that the relayer can use to provide its own interpretation of a cache that exposes get and set functions.
=> improve: reintroduce hub pool caching

src/interfaces/ConfigStore.ts, src/lpFeeCalculator/rateModel.ts, src/pool/TransactionManager.ts
Import the following from the UMA repo:
- RateModelDictionary class (+ related definitions).
- TransactionManager closure.
It was very simple to hoist the ConfigStore interface over to the new local definitions, so that has been applied here. Subsequent changes are needed for the TransactionManager; those will be applied in a follow-up commit so the modifications are explicitly identified.
=> refactor: New UMA SDK imports

src/clients/HubPoolClient.ts, src/clients/SpokePoolClient.ts
This should not happen, in general, but this adds a check to throw an error if a future timestamp is ever requested.
=> fix: disallow computing lp fees for future timestamps

src/pool/poolClient.e2e.ts
This test falls back to public RPC endpoints, so it's necessary to bump the timeout to account for rate-limiting. Also, jest.setTimeout() changes the global timeout for the test file, so ensure that the increased timeout only applies to the specific test in question.
=> chore: Bump poolClient e2e test timeout

package.json, src/clients/HubPoolClient.ts, src/clients/SpokePoolClient.ts
This reverts commit a43657b3ad34c7239b5b88264ce71c0fcf767209.
The relayer-v2 tests are not well equipped yet to handle this change
Ideally this change gets reimplemented but perhaps at the relayer/dataworker level
=> revert: don't error when handling future quote timestamps

package.json, src/constants.ts
We should support `transferThreshold` before but not including version 2
=> fix: Move transfer threshold max supported version down to current version

package.json
This change augments the CI build script to ensure that we are building the full set of TSC files
=> chore: bump version & change pre-publish step

src/utils/common.ts
This unfortunately introduces direct Web3.js dependencies, but we need to import it as-is before we can clean it up.
[update]: No issue anymore - this is a very simple change now.
=> refactor: Import createFormatFunction + associated from UMA

package.json, yarn.lock
Result of running `npx yarn-deduplicate yarn.lock`.
This effectively prunes our dependency list to a list of needed modules.
=> chore: deduplicate yarn lock file

test/fixtures/UmaEcosystemFixture.ts
Originally proposed to relayer-v2.
=> refactor: Drop UMA interfaceName

src/relayFeeCalculator/relayFeeCalculator.ts
We already had these defined locally, so the UMA imports were unnecessary.
=> refactor: Use local helpers instead of UMA helpers

src/clients/SpokePoolClient.ts, src/utils/SpokeUtils.ts
There is a bug in the binary search function of the SpokePoolClient where, if the deposit ID is outside the range, then it still returns a non-failing value. This PR changes that by adding an additional safety check to ensure that the largest deposit ID is greater than or equal to the target search.
=> fix: resolve bug in spoke pool deposit search

package.json, src/utils/DepositUtils.ts, src/utils/ValidatorUtils.ts, src/utils/index.ts, test/validatorUtils.test.ts
We should allow our queries to _self-heal_ if they detect a malformed deposit. This will check if a deposit returned from the cache is malformed. If it is found to be malformed, we will ignore it and re-cache a correct version.
=> feat: failover historic query if deposit is malformed

package.json, src/relayFeeCalculator/relayFeeCalculator.ts, test/relayFeeCalculator.test.ts
We shouldn't allow a default backup if a token doesn't have an associated default/overridden cost config. This is indicative of a malformed configuration.
=> improve: enforce no capital cost default

.github/workflows/test.yml
We should be using the newly defined `NODE_URL_1` secret for our `test/common.test.ts` test file.
This PR may be updated in the event that slight tweaks need to be made to the `.github/workflows/test.yml` file.
=> feat: use new node_url for unit test

src/utils/DepositUtils.ts
Also add a `resolveDepositMessage()` helper to make it simple for callers to fetch the correct message for a given Deposit object.
=> refactor: Relocate Deposit utilities from relayer-v2

package.json, src/clients/UBAClient/UBAClientWithRefresh.ts
This PR uses the `super()` call to set the caching client within the `BaseAbstractClient`
=> improve: supply super() with cache in UBAClient

src/utils/BlockUtils.ts
The underlying Provider instance is actually backed by multiple RPC provider backends, and they can run be out of sync at various times. This change will catch and report those instances, and will also help to avoid them by subtracting an offset to the latest block number to give a greater chance of getting coherent responses from all RPC providers.
=> improve(BlockUtils): Better robustness on average block time resolution

src/clients/HubPoolClient.ts, src/constants.ts, src/utils/CachingUtils.ts
This caching lag is used to store utilization cached values read from the HubPoolClient, and deposit structs
Signed-off-by: nicholaspai <npai.nyc@gmail.com>
=> improve(constants): Allow HubPoolClient constructor to override default caching safe lag

package.json, src/clients/HubPoolClient.ts, src/utils/BlockUtils.ts, test/utils/utils.ts
This change introduces the function `getCachedBlockForTimestamp` into the SDK. All calls to blockfinder's `getBlockForTimestamp` have been diverted to either an available `hubPool.getBlock(timestamp: number)` function (which leverages `getCachedBlockForTimestamp` or with `getCachedBlockForTimestamp` directly.
The original code block is:
```
/**
* @notice Get the block number for a given timestamp fresh from on-chain data if not found in redis cache.
* If redis cache is not available, then requests block from blockFinder.
* @param chainId Chain to load block finder for.
* @param timestamp Approximate timestamp of the to requested block number.
* @param blockFinder Caller can optionally pass in a block finder object to use instead of creating a new one
* or loading from cache. This is …
```
=> feat: include cache in SDK block finder

package.json
=> fix: Remove vc:dev yarn script target

src/utils/NetworkUtils.ts, src/utils/common.ts
It was reported a few weeks ago that a gas spike on mainnet caused deposits destined for Base to be underpriced; I couldn't figure out why this would be the case for Base but not Optimism, but this may have contributed.
As part of this, add a simple utility to indicate whether a chain ID is an OP stack implementation.
=> fix: Better gas estimation for Base

.husky/pre-commit
Enforcing this on commit is a productivity killer and I have to keep typing --no-verify when committing.
If we want additional checks before code is submitted to GitHub, I'd probably be keen to explore a pre-push hook instead. But I am generally happier if CI is instrumented to catch everything so that we don't waste local developer time waiting for standard checks to occur.
=> chore: Don't force lint, build & test on commit

package.json, src/clients/SpokePoolClient.ts, test/SpokePoolClient.SpeedUp.ts
This PR optimizes compute time for the case where there is a speed up deposit in a SpokePoolClient update.
Currently the algorithm for adding speed up data to deposits is:
- load all speed up events into memory
- loop through all deposits already stored in memory, detect if there is a speed up event newly saved into memory for the deposit, and update the deposit
We needlessly loop through all deposits since there are expected to very few speed ups in a given lookback window relative to the number of deposits loaded. Instead, the proposed algorithm is:
- load all speed up events into memory
- for each new speed up data newly saved, detect if there is a deposit data stored in memory matching the speed up, and update the deposit
Merge state
=> improve(SpokePoolClient): Optimize algorithm for appending speed up data to deposits

package.json, src/clients/AcrossConfigStoreClient/AcrossConfigStoreClient.ts, src/clients/mocks/MockConfigStoreClient.ts, src/relayFeeCalculator/chain-queries/optimism.ts, test/SpokePoolClient.ValidateFill.ts
Precursor to support https://github.com/across-protocol/relayer-v2/pull/1085
=> improve(ConfigStoreClient): Improve logs and optimistically don't load `latestBlockNumber` if passed in as search config toBlock

package.json, src/clients/HubPoolClient.ts, src/utils/BlockUtils.ts
If the caller supplies a sensible hint then this will skip the initial lower-bound block estimation, which can be wildly inaccurate in cases where the average block time has changed (especially reduced) over time. This is also nice because one of the main beneficiaries of this is in the relayer, the hinted lowBlock can be set statically, so it has a much greater chance of being served out of the RPC provider cache.
=> improve(BlockFinder): Allow the caller to supply hints

src/clients/HubPoolClient.ts, src/clients/SpokePoolClient.ts, src/clients/mocks/MockSpokePoolClient.ts, src/interfaces/HubPool.ts, src/utils/BlockUtils.ts, test/HubPoolClient.Utilization.ts, test/SpokePoolClient.ValidateFill.ts, test/utils/utils.ts
This change removes a source of significant inefficiency in the HubPoolClient. The pre-existing implementation processes each Deposit's realizedLpFeePct independently, but in parallel. In cases where there are n deposits with the same quoteTimestamp, this results in n concurrent searches for the underlying block number. Additionally, when there are n deposits with matching originToken and quoteTimestamp (as can easily happen with the popular tokens like (W)ETH and USDC) this results in similarly duplicate queries for the "opening" HubPool utilization at the resolved block number.
This commit updates the implementation as follows:
- Pass the set of Deposits to be computed by the HubPoolClient as an array, rather than individually.
- Filter quoteTimestamps for uniqueness before resolving …
=> improve(HubPoolClient): Process LP fees in batch

package.json, src/clients/HubPoolClient.ts
The last change to HubPool utilization computation ended up reusing the same cache key for post-relay utilization, but storing the value with a different format (1 number instead of 2 comma-separated).
This PR replaces the existing getUtilization() function because it's no longer used, and adds a temporarily change to the post-relay utilization key to avoid collisions until the original keys are ejected.
This was caught during final local testing of the PR to bump sdk-v2 within relayer-v2.
=> fix(HubPoolClient): Avoid utilization cache collisions

src/clients/HubPoolClient.ts, src/clients/SpokePoolClient.ts, src/clients/UBAClient/UBAClientUtilities.ts, src/clients/UBAClient/UBAClientWithRefresh.ts, src/clients/mocks/MockSpokePoolClient.ts, test/SpokePoolClient.ValidateFill.ts, test/UBAClient.validateFlow.ts, test/UBAClientUtilities.ts, test/utils/HubPoolUtils.ts
Downstream users of the HubPoolClient and the SpokePoolClient expect that the `latestBlockNumber` is the latest block seen by the appropriate providers. However, this is not the case if the clients' `searchConfig.toBlock` lags the HEAD block on the chain, which is possible in production especially since SpokePoolClient updates take a long time to run and are done in parallel.
=> improve(Clients): Set latestBlockNumber equal to latest block searched and remove redundant latestBlockSearched

src/clients/HubPoolClient.ts, src/clients/SpokePoolClient.ts
In the event that the SpokePoolClient searchConfig toBlock is set externally, subsequent updates will always be ignored.
=> fix(SpokePoolClient): Unset searchConfig toBlock after update

src/clients/SpokePoolClient.ts
To be used in relayer-v2, but it's a generally useful feature so it
makes sense to define it centrally.
=> feat(SpokePoolClient): Support filtering deposits by block number

package.json, src/clients/AcrossConfigStoreClient/AcrossConfigStoreClient.ts, src/clients/BaseAbstractClient.ts, src/clients/HubPoolClient.ts, src/clients/SpokePoolClient.ts, src/clients/UBAClient/UBAClientUtilities.ts, src/clients/UBAClient/UBAClientWithRefresh.ts, src/clients/mocks/MockConfigStoreClient.ts, src/clients/mocks/MockHubPoolClient.ts, src/clients/mocks/MockSpokePoolClient.ts, src/transfers-history/services/SpokePoolEventsQueryService.ts, src/utils/BlockUtils.ts, src/utils/BundleUtils.ts, src/utils/SpokeUtils.ts, test/HubPoolClient.RootBundleEvents.ts, test/SpokePoolClient.RefundRequests.ts, test/SpokePoolClient.ValidateFill.ts, test/UBAClient.validateFlow.ts, test/UBAClientUtilities.ts, test/utils/HubPoolUtils.ts, yarn.lock
The current name `latestBlockNumber` usually implies that it should return the HEAD block for the provider but the way its used, it 
should actually return the latest block searched by the client.
=> improve: rename `latestBlockNumber` to `latestBlockSearched`

src/utils/SpokeUtils.ts
This was an omission in the previous commit. getRelayHash() permits amount, realizedLpFeePct, relayerFeePct or message to be undefined.
=> fix: Include message in relay hash

package.json, src/clients/SpokePoolClient.ts, src/utils/DepositUtils.ts, test/SpokePoolClient.ValidateFill.ts
This change provides additional information to the caller of queryHistoricalDepositForFill(). In the case that a fill is not found, a cause code is associated:
- 0: The deposit ID was invalid for the SpokePool (i.e. cannot exist).
- 1: The deposit ID was valid, but it wasn't found within scraped data (i.e. maybe the RPCs aren't serving it in eth_getLogs() requests).
- 2: The deposit ID was valid, but one or more fields in the corresponding deposit were mismatched (i.e. the fill was invalid).
This is most interesting for case (1), where there's a reasonable indication that the deposit should be held within the SpokePoolClient's deposit map, but isn't. This indirectly acts like a qualitative measure for RPC provider responses and will allow the upper layers to dynamically revert to more …
=> feat: Propagate invalid fill reasons to caller

src/apiClient/abstractClient.ts
The ChainId definition is only a number, so define it directly in the apiClient. Done in anticipation of the transfers-client implementation being removed from the sdk, pending confirmation as to whether anyone actually uses it.
=> chore: Decouple transfers-history from apiClient

src/relayFeeCalculator/relayFeeCalculator.ts
getFeePercent() already obtains the destination token decimals via a call to getTokenInformationFromAddress(), so there's no need for a separate lookup via getTokenDecimals().
=> improve(relayFeeCalculator): Skip redundant decimals lookup

src/utils/SpokeUtils.ts, test/SpokePoolClient.fills.ts
This is transparently compatible with v3 RelayData, which does not directly include the destinationChainId.
=> improve(findFillBlock): Source destinationChainId from SpokePool

test/relayFeeCalculator.test.ts
Introduced unintentionally in the previous commit, this prevents parallel test execution and suppresses all other tests from running.
=> fix: Remove .only test constraint

package.json, src/clients/HubPoolClient.ts
We need this as part of the new relayer finalizer for L1 -> L2 finalizations. We can use the `executedRootBundle` in the search for transaction receipts that contain outbound multi-chain transactions that require finalizations.
=> improve(hubpool): expose executedRootBundle 

package.json
The current version is v0.20.1; v0.20.2 hasn't been built yet.
=> fix: Revert last package version bump

src/utils/V3Utils.ts
`isV3` can be used by the dataworker and relayer to switch how it creates RelayerRefundLeaves/SlowFillLeaves and also to know when v3 interfaces are available to be called on-chain
=> feat: Export V3 version

src/clients/SpokePoolClient.ts, src/clients/mocks/MockSpokePoolClient.ts, test/SpokePoolClient.fills.ts
These will be useful for the dataworker functions (beginning to be implemented in https://github.com/across-protocol/relayer-v2/pull/1155 ) that have to deal with expired deposits. We need to be able to know when a deposit is expired (comparing its fill deadline TIMESTAMP with a bundle BLOCK NUMBER), and also whether our spoke pool clients have enough of a lookback to fetch expired deposits for a bundle
=> feat: Add oldest time searched to SpokePoolClient

src/utils/abi/contracts/SpokePoolV3.json
This ABI can be used by sdk-v2 and relayer-v2 code in advance of the pending bump to contracts-v2.
=> feat: Import SpokePoolV3 ABI

package.json, src/clients/SpokePoolClient.ts, src/utils/BundleUtils.ts, src/utils/V3Utils.ts
Adds functions we can override in a downstream MockSpokePoolClient to make unit tests more precise
=> feat: Add spoke pool client functions to support BundleDataClient unit tests in relayer-v2

src/interfaces/SpokePool.ts
This isn't used in the SDK or relayer repositories.
=> refactor: Remove redundant SlowFill type

package.json, src/clients/SpokePoolClient.ts, src/clients/mocks/MockSpokePoolClient.ts, src/interfaces/SpokePool.ts, src/utils/SpokeUtils.ts, src/utils/V3Utils.ts
This PR makes two changes:
- Reorganise common type definitions around v*RelayData types.
- Rename type definitions v* -> V* to fit type style norms (proposed by
James).
The former is done out of recognition that RelayData definitions
actually drive a lot of the activity in the bots, and this is even
moreso the case with v3. Anchoring types around RelayData definitions
shortens the set of definitions needed in the SpokePool interfaces file,
and also gives assurance that the bots can correctly derive a RelayData
object out of a Deposit, Fill, or even a SlowFillRequest.
=> refactor: Re-organise types around RelayData

test/abi.ts
This test suddenly started failing after I'd merged in the latest ABI update. I identified the issue to be that my editor has saved a swap file in the same directory, and the test was incorrectly trying to use it.
=> improve: Ignore dotfiles in ABI test

src/interfaces/HubPool.ts, src/interfaces/SpokePool.ts, src/utils/V3Utils.ts
This change introduces V3 defintions for RelayerRefundExecution, but also recognises that the existing RelayerRefundExecution SpokePool definition has significant overlap with the HubPool RelayerRefundLeaf type, so it now inherits most of the definition from the HubPool.
=> feat: Define V3RelayerRefundExecution

src/utils/V3Utils.ts
This is the first PR in the push to use generics to avoid casting: https://github.com/across-protocol/sdk-v2/pull/501#discussion_r1476621443.
This allows you to pass in, for instance, a DepositWithBlock, a Deposit, or any union of structs with "originToken" | "inputToken" to isV2Deposit(), and it will correctly pick the right member of the union.
=> feat: replace type guards with generics to avoid casting

package.json, src/utils/NetworkUtils.ts, yarn.lock
A use for this has been identified in the relayer repository, but it's
also likely to be needed for Orbit chains.
While here, update the OP stack chain IDs as well, since we now have new 
test chains.
=> feat: Utility for identifying Arbitrum chains

src/clients/SpokePoolClient.ts
- Support dynamic population of _queryableEventNames(), subject a filter to avoid accidentally querying random events that we aren't actually interested in.
- Ensure empty speedup arrays are not passed to Array.reduce().
- Ensure to append originChainId on V3FundsDeposited events.
The Array.reduce() issue was originally identified by Nick.
=> feat(SpokePoolClient): Improvements and corrections

src/utils/FlowUtils.ts, src/utils/SpokeUtils.ts
This pivots fill comparison for v3 towards using relay data hashes. This is simpler code and should also be safer, since this code inherits existing assurances about the RelayData being complete.
=> improve: Upgrade fill/deposit comparison utils

src/clients/mocks/MockSpokePoolClient.ts, src/interfaces/SpokePool.ts
These were misaligned with the contracts; testing in the relayer repository has flushed it out.
=> fix: Align Fill[V3]Relay execution info types

src/caching/Arweave/ArweaveClient.ts, test/arweaveClient.ts
We should explicitly handle the path where we are out of gas. This should unwind the stack to the calling function.
=> improve(arweave): handle out of gas error

package.json, src/caching/Arweave/ArweaveClient.ts
Large enough Arweave balances (5B+ Arweave balances) are returned to the client in scientific notation (i.e. `5e+24`). This PR handles the sci notation output.
=> fix(arweave): resolve BN parse error for large Arweave balances

package.json, src/caching/Arweave/ArweaveClient.ts, test/arweaveClient.ts
Allows the Arweave client to resolve data by tags. This will be helpful for use in the relayer-v2 so that we don't submit duplicate data.
=> feat(arweave): search by topics

.github/workflows/test.yml, package.json, test/arweaveClient.ts, yarn.lock
This PR internalizes the instantiation of an ArLocal local testnet for testing txns to/from Arweave. Note that the changes made in this PR still start an ArLocal server, but the management of the server is encapsulated within the unit test and a secondary process doesn't need to be manually run.
=> improve(arlocal): avoid second process

src/utils/FlowUtils.ts
Hashing can be expensive when it's run in a tight loop (i.e. when iterating over a complete array). Identified by Nick when investigating performance issues.
=> improve(FlowUtils): Avoid hashing obvious fill mismatches

src/relayFeeCalculator/chain-queries/baseQuery.ts, src/relayFeeCalculator/relayFeeCalculator.ts, src/utils/SpokeUtils.ts
This is a simple change to permit estimating v3 fills. This is used by the relayer, but also the FE. It'll be necessary for simulating messages with fills to recipients who only support handleV3AcrossMessage(), and the relayer also needs it prior to v3 going live.
=> feat(relayFeeCalculator): Support estimating v3 fills

package.json, src/relayFeeCalculator/relayFeeCalculator.ts
When using a safe output amount for simulation, the gas fee percent was wrong. The calculation used the lower safe amount of `safeOutputAmount` instead of the initial `amountToRelay` for deriving the percentage.
=> fix: gas fee percent

package.json, src/clients/SpokePoolClient.ts, src/relayFeeCalculator/relayFeeCalculator.ts
Missing `originChainId` needs to be appended to this partial event queried from eth_getLogs
=> fix: Add `originChainId` to partial deposit queried from eth_getLogs

package.json, src/utils/TokenUtils.ts
Allow overriding l1 chain id when trying to get l2 token address.
=> fix: get l2 token address utils

package.json, src/clients/HubPoolClient.ts
This follows the pattern established in the SpokePoolClient, where `EnabledDepositRoute` overriddes `searchConfig.fromBlock` on the first update.
This will be used in the relayer to reduce the lookback for events related to root bundles, since there's no need to query those all the way back to HubPool genesis.
=> improve(HubPoolClient): Permit selectively overriding search config

package.json, src/caching/Arweave/ArweaveClient.ts
We should be passing the expected inputs to the logger as defined here: https://github.com/UMAprotocol/protocol/blob/2f300fd7f24367aed758baa0367241d7fed2d599/packages/logger/src/logger/SlackTransport.ts#L5-L23
=> fix(logger): use proper slack transport inputs

package.json, yarn.lock
This PR bumps the `@eth-optimism/sdk-v2` so that our CircleCI build works every time.
--
Reasoning: we want to have this PR added to our codebase (https://github.com/ethereum-optimism/optimism/pull/9805)
Currently, the CircleCI occasionally fails due to an issue with the `@eth-optimism/sdk` pre-install scripts. By upgrading the optimism package to include the PR listed above, the hope is that we can mitigate these occasional failed builds.
I have been working closely with @evaldofelipe to diagnose/triage this issue.
=> improve(sdk): bump optimism sdk

package.json, src/utils/ArrayUtils.ts, src/utils/SpokeUtils.ts, test/ArrayUtils.ts
This allows the caller to be ignorant of the number of fill status requests they are sending.
=> improve(utils): Support chunking fillStatusArray queries

package.json, src/caching/Arweave/ArweaveClient.ts, src/constants.ts
We should be tagging Arweave by version in addition to other attributes. This change introduces a tag version & a graphql filter to the `getByTopic` function.
=> improve(arweave): include app version

src/utils/BlockUtils.ts
This avoids getBlockNumber() and subsequent concurrent getBlockByNumber() queries to determine the average block time over the past 120 blocks, which is a prerequisite when setting SpokePoolClient search settings.
=> improve(BlockUtils): Preset Linea block time to 3 seconds

src/utils/EventUtils.ts, test/relayFeeCalculator.test.ts
There is a bug in the spreadEvent function right before the recurrence. Previously, we were getting the keys of 
```
args[key].filter((key: string) => isNaN(+key)
```
which would first filter the array of non-numeric keys. Whereas we should have gotten the keys of `args[key]` and filtered on the keys.
=> hotfix(spreadEvent): fix recurrence step

src/constants.ts, src/utils/BlockExplorerUtils.ts, src/utils/NetworkUtils.ts
This centalises our chain definitions and eliminates an annoying import workaround that was previously needed for PUBLIC_NETWORKS to be used in the FE.
=> refactor(utils): Defer to constants-v2 for chain definitions

package.json, src/constants.ts
We had a change to our deposit that will break previous bundle data.
=> improve: arweave structure version bump

src/clients/SpokePoolClient.ts
Not sure how this was previously able to pass any tests. Perhaps because no caller currently specifies the timeout, so the assert() is never called.
=> fix(SpokePoolClient): Import assert

package.json, src/clients/SpokePoolClient.ts
Due to unintentional collateral damage in the relayer tests, which I had incorrectly attributed to a `yarn link` issue.
=> fix: Revert SpokePoolClient update timeout

src/clients/index.ts
This is needed in relayer-v2 where the SpokePoolClient will be overridden.
=> chore(clients): Export SpokePoolUpdate type

package.json, src/clients/AcrossConfigStoreClient/AcrossConfigStoreClient.ts
Otherwise any subsequent update() calls will resolve that fromBlock > toBlock, and no update will occur.
=> fix(ConfigStoreClient): Unset searchConfig.toBlock after update()

src/clients/SpokePoolClient.ts
If the provided SpokePool contract doesn't have access to `cctpTokenMessenger` then it can't have `cctpTokenBridgingEnabled` set to true.
=> fix(spokepool client): hasCCTPTokenBridge

package.json, src/utils/Multicall.ts, src/utils/index.ts
This has immediate application in the relayer TokenClient but surely has additional uses cases in other parts of the codebase. Inspired mostly by the corresponding implementation in the FE.
=> feat: Add multicall3 aggregate helper

package.json
The `relayFeeCalculator` changes are breaking. We should do a minor bump.
=> chore(version): bump to 0.24.0

package.json, src/contracts/hubPool.ts
The way we were tracking pool fees was broken. This is reflected in the FE. This regression was introduced here: https://github.com/across-protocol/sdk-v3/pull/389
=> fix(pool): correct fees output

package.json, src/relayFeeCalculator/chain-queries/baseQuery.ts, src/relayFeeCalculator/relayFeeCalculator.ts, src/utils/common.ts
While monitoring the speed of the `GET /suggested-fees` handler, I noticed some areas of improvement. For example, in the trace of the attached screenshot, you can see all RPC requests triggered by the `relayFeeCalculator`. This PR aims to reduce the number of those and parallelize a few by:
- allow passing in `gasPrice` to `getGasCosts` to allow caching of that value to prevent RPC calls
- allow passing `chainId` to `estimateTotalGasRequiredByUnsignedTransaction` to prevent additional RPC if chain already known
- for OP stack:
- set `gasLimit` with already retrieved value to prevent redundant RPC call
- concurrently call parts of `estimateTotalGasCost` for speed up
=> refactor: improve `getGasCosts` rpc calls

package.json, src/clients/SpokePoolClient.ts, src/clients/mocks/MockSpokePoolClient.ts
This feature was introduced in advance of the CCTP rollout but it appears to be unused in the bots.
=> refactor(SpokePoolClient): Drop CCTP queries

src/clients/SpokePoolClient.ts, test/SpokePoolClient.DepositRoutes.ts
We don't rely on these functions [anymore](https://github.com/across-protocol/relayer-v3/commit/d1a6c65478fed946df57958a74d2a4f6a4f6192a) in the Relayer so delete them to avoid future dependencies on them.
We favor instead mapping l1 and l2 tokens using PoolRebalanceRoutes which requires querying only the Hub chain as opposed to all Spoke chains, which is overall much faster.
=> improve(SpokePoolClient): Delete some depositRoute functions

src/clients/SpokePoolClient.ts, src/interfaces/SpokePool.ts, test/SpokePoolClient.SpeedUp.ts, test/SpokePoolClient.ValidateFill.ts, test/SpokePoolClient.v3Events.ts
This PR renames `originatesFromLiteChain` and adds a corresponding check for the destination chain as well.
=> fix: add field to mark if destination chain is lite

package.json, src/utils/NetworkUtils.ts
As we begin to introduce `tryMulticall` into the relayer, the `MulticallerClient` will need to be aware of whether it is calling a spoke pool or hub pool contract (to determine whether it can even call `tryMulticall`). One approach is to first check if the contract's chain ID we are calling is one which has a hub pool implementation. It would be ideal to introduce this code into the sdk, where there already exists a set of functions which performs similar checks with our other chain IDs.
=> improve(NetworkUtils): add chainIsL1Function

src/clients/SpokePoolClient.ts
We have a few different variants on "get fill" in the SpokePoolClient, but none that specifically meet the needs of a pending feature in the relayer, so I'll tentatively propose to add it here.
=> feat(SpokePoolClient): Permit querying a fill for a single deposit

e2e/oracle.e2e.ts, src/gasPriceOracle/oracle.ts
According to the last paragraph in  https://docs.scroll.io/en/developers/transaction-fees-on-scroll/#l1-originated-transactions, we can use the legacy RPC call `eth_gasPrice` to determine the gas price on Scroll:
> If your system supports off-chain mechanisms, you can also call eth_estimateGas and eth_gasPrice on any Scroll RPC node to get an estimate of the gas required for a given transaction.
Closes ACX-2356
=> feat: add scroll to gas price oracle

package.json, src/relayFeeCalculator/chain-queries/baseQuery.ts, src/relayFeeCalculator/relayFeeCalculator.ts, src/utils/common.ts, test/common.test.ts
Some integrators flagged an issue for fee estimation when setting custom messages. After some digging, a workaround is to set a large enough hardcoded gas limit and a gas price when calling `eth_estimateGas`. E.g. the following `eth_estimateGas` call fails where `gas` and `gasPrice` are not set:
```bash
curl https://arb1.arbitrum.io/rpc \
-X POST \
-H "Content-Type: application/json" \
--data '{"method":"eth_estimateGas","params":[{"from":"0x428ab2ba90eba0a4be7af34c9ac451ab061ac010","to":"0xe35e9842fceaca96570b734083f4a58e8f7c5f2a","data":"0x2e3781150000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000a4b1000000000000000000000000ccb0be73bc7386db701006762dd7f8638d176d48000000000000000000000000ccb0be73bc7386db701006762dd7 …
```
=> fix: set gas limit and price for fill estimation

package.json, src/relayFeeCalculator/relayFeeCalculator.ts
The `gasFeePercent()` function always attempts to call into CoinGecko. It's possible that its API call returns faster than our logic and triggers a 500 internal server error.
=> fix: cg lookup edge case

package.json, src/relayFeeCalculator/chain-queries/factory.ts, src/relayFeeCalculator/chain-queries/polygon.ts, yarn.lock
For a redeployed Redstone SpokePool.
=> chore: Bump contracts

package.json, src/clients/SpokePoolClient.ts, src/utils/DepositUtils.ts
When the fill is totally malformed and filters on values that never existed (i.e. the real deposit for this deposit ID specified an alternative destinationChainId), it will skip returning the _actual_ deposit for this deposit ID.
=> fix: Correctly resolve historical deposits

package.json, src/providers/rateLimitedProvider.ts, src/providers/retryProvider.ts, yarn.lock
We can assume that the user needs to pass a logger to get logging, and since the uma logger extends Winston we can just use that.
Change:
1. Remove uma/logger (vuln package)
2. Use `Logger` type in lieu of uma/logger type
3. RateLimitedProvider will not have a fallback logger
=> improve: remove uma logger dep

package.json, src/providers/alchemy.ts, src/providers/index.ts, src/providers/infura.ts, src/providers/types.ts, src/providers/utils.ts
Alchemy has recently added support for reusing the same API key across multiple networks. Observing that both Alchemy and Infura use reasonably-predictable symbolic names for their endpoints (with a small number of exceptions), it's fairly advantageous to programatically resolve the endpoint URLs from a chain ID and an API key. This permits a single API key to be defined per provider, rather than the existing requirement of having to define each individual RPC configuration in the environment.
This change deliberately avoids trying to encode an env-var format for reading keys from the environment; that should permit maximum reuse amongst different applications.
=> feat: Cheat codes for resolving provider URLs

package.json, src/clients/BundleDataClient.ts, src/clients/BundleDataClient/BundleDataClient.ts, src/clients/BundleDataClient/index.ts, src/clients/BundleDataClient/utils/DataworkerUtils.ts, src/clients/BundleDataClient/utils/FillUtils.ts, src/clients/BundleDataClient/utils/MerkleTreeUtils.ts, src/clients/BundleDataClient/utils/PoolRebalanceUtils.ts, src/clients/BundleDataClient/utils/SuperstructUtils.ts, src/clients/BundleDataClient/utils/index.ts, src/clients/BundleDataClient/utils/shims.ts, src/clients/index.ts, src/interfaces/BundleData.ts, src/interfaces/index.ts, src/utils/AddressUtils.ts, src/utils/ContractUtils.ts, src/utils/ObjectUtils.ts
This PR aims to migrate the Bundle Data Client and its supporting functions into the SDK
--
Review code diffs since:
1. The initial copy/paste of the bundle data client: https://github.com/across-protocol/sdk/compare/de738a9371200d3b2df08e6bf15be540ea5695d2...james/acx-2443-refactor-sdk-contract-clients
2. The initial copy/paste of the top level supporting functions: https://github.com/across-protocol/sdk/compare/366a96f74699ac68f0fe5e96d8b6ff1a955269db...james/acx-2443-refactor-sdk-contract-clients
3. The initial copy/paste of the supporting functions needed for the supporting functions: https://github.com/across-protocol/sdk/compare/6fcff5db35d626d3e71f2396836bb055d640c377...james/acx-2443-refactor-sdk-contract-clients
4. The initial copy/paste of the supporting functions for step 3: …
=> improve: migrate bundle data client

src/clients/SpokePoolClient.ts, src/interfaces/SpokePool.ts
In order to index 'RequestedSpeedUpV3' events, the indexer needs to get the speedUps map from the SDK.
=> feat(SpokePoolClient): getter function for speedUps

test/common.test.ts
Seeing lots of "noNetwork" errors on CloudFlare.
=> fix(test): Use less unreliable RPC provider

src/caching/Arweave/ArweaveClient.ts
On rare occasions the Arweave id we query is not yet accessible, leading to temporary 404 errors in the dataworker. This wraps the requests in a try/catch to prevent the dataworker from throwing when these 404 errors happen. As an example:
```
2024-09-04 18:46:59 [warn]: {
"at": "ArweaveClient:getByTopic",
"message": "Bad request for Arweave topic KBhB2uBPhQU-mXLOykRUQQQjjKThCLXRq4ncNVUhMJg: AxiosError: Request failed with status code 404",
"run-identifier": "1819360f-26f0-45ad-9a56-471029fdab8e"
}
```
Closes ACX-2054
=> improve(ArweaveClient): handle 404 errors

test/common.test.ts
The functionality exercised by this test needs an overhaul to work
against hre, so just drop its number of iterations for now.
=> fix(test): Reduce RPC susceptibility in test

package.json, src/providers/index.ts, src/providers/speedProvider.ts, src/relayFeeCalculator/chain-queries/baseQuery.ts, src/relayFeeCalculator/relayFeeCalculator.ts, src/utils/common.ts
This PR enables two performance tweaks in the API:
- Using a cached `gasUnits` value for a fill - this saves an RPC request in the fee calculator
- Using the `SpeedProvider` which makes use of `Promise.any`
=> feat: allow usage of cached `gasUsage` + `SpeedProvider`

package.json, src/clients/BaseAbstractClient.ts, src/clients/index.ts
This is useful in the looping model where some SpokePoolClient instances will be updated faster than others. The looping model doesn't wait for the SpokePoolClient to be ready, so it's useful to signal that update did not occur, rather than assuming that it did.
=> improve(clients): Add "NotReady" failure cause

src/providers/retryProvider.ts
In cases where we threw the QuorumError early, we were not logging any details of the mismatch.
=> improve(RetryProvider): improve logs for quorum mismatch or failures

package.json, src/gasPriceOracle/adapters/polygon.ts, src/priceClient/adapters/baseAdapter.ts
Changes:
- Bump timeout from 1.5s to 2s.
- Reduce retries from 1 to 0.
- Enforce a minimum of 30 Gwei priority on gas station failure.
- Set HTTP user agent to "across-protocol" and permit overriding via the environment.
- Incidental cleanup.
This change is made on request from the Polygon team to support troubleshooting of repeat timeouts on the GasStation API.
=> chore: Update Polygon GasStation implementation

.eslintrc.js, package.json, src/clients/AcrossConfigStoreClient/AcrossConfigStoreClient.ts, src/clients/HubPoolClient.ts, src/clients/SpokePoolClient.ts, src/clients/mocks/MockConfigStoreClient.ts, src/clients/mocks/MockEvents.ts, src/clients/mocks/MockHubPoolClient.ts, src/clients/mocks/MockSpokePoolClient.ts, src/contracts/utils.ts, src/interfaces/Common.ts, src/utils/EventUtils.ts, test/HubPoolClient.DepositToDestinationToken.ts, test/SpokePoolClient.v3Events.ts, test/common.test.ts
The ethers Event type is an extension of the underlying Log type, which is actually the type that contains almost all of the event data that the SDK needs for Across. Since Event extends Log, it's safe to narrow the scope of the RPC data down to a Log type. This significantly reduces the delta to viem's Log type and is a key stepping stone for viem and ethers to be used interchangeably for RPC interfacing & transport.
It additionally seems like this simplification _might_ also support Solana events (...with some eventual coercion).
It should be noted that this change touches some code that makes a lot of assumptions about the event types that are being handled, and there are some warts. I've tried not to make things any less safe than they already are, but this code is generally in need …
=> refactor: Replace ethers Event with Log

package.json, src/clients/HubPoolClient.ts
We need to expose these elements in the indexer so that we can dynamically track l1 <-> l2 token lookups
=> improve(hubpool): expose l1TokensToDestinationTokens

package.json, src/clients/HubPoolClient.ts
The variable `l1TokensToDestinationTokensWithBlock` is a nested record of `DestinationTokenWithBlock[]` which includes a `transactionHash` field from the `SortableEvent` interface.
We were not assigning `transactionHash` in the hub pool client's `update()` function. This was uncovered during work on the indexer.
=> fix: include tx hash in `l1TokensToDestinationTokensWithBlock`

package.json, src/utils/common.ts
When passing cached gas prices into the relay fee calculator in the API, `estimateGas` was erroring. I think this is due to the reason that we provided the value into the estimate method as well.
=> fix: do not pass gasPrice to estimateGas

src/clients/SpokePoolClient.ts
The deposit outputAmount is already a BigNumber, so there's no need to
pass it through toBN(). This function is typically called repeatedly in 
a tight loop by the relayer so it makes sense to drop the inefficiency.
=> improve(SpokePoolClient): Drop unnecessary BN conversions

package.json, src/clients/SpokePoolClient.ts
The SpokePoolClient is currently throwing semi-regular errors on update. This seems to be particularly occurring against Polygon. The underlying reason for this is that the RPC quroum system is performing an eth_call against multiple providers, tagged at the latest block number as resolved by only one of them. Some providers may not have resolved that block number yet, in which case the query fails.
The instance of this can presumably be reduced by bundling the two calls where this occurs into a single SpokePool multicall. As a side-benefit, it will reduce RPC consumption.
=> improve(SpokePoolClient): Multicall latestBlock updates

package.json, src/relayFeeCalculator/chain-queries/baseQuery.ts, src/utils/common.ts
Additionally return raw unpadded `gasUnits` in `getGasCosts` method. This allows us to correctly make use of a cached value by caching the unpadded `gasUnits` value and passing that in.
=> feat: return raw `gasUnits` without padding

package.json, src/clients/SpokePoolClient.ts
The `oldestTime` attribute is only needed for a very specific check when validating block ranges in the dataworker. Removing it from the standard SpokePoolClient update flow is a simplification for non-dataworker use-cases - i.e. relayer, monitor, finalizer. The dataworker can instead resolve the timestamp of the searchConfig fromBlock on demand.
The underlying motivation for this change is to simplify the interface between the relayer and the external SpokePool listener processes in order to make way for additional updates.
=> refactor: Remove SpokePoolClient oldestTime lookup

src/utils/NetworkUtils.ts
`Right operand of ?? is unreachable because the left operand is never nullish.`
=> nit: remove unneeded null coalesce

src/providers/retryProvider.ts
Debug logging has shown that the existing logic unconditionally completes the for() loop `this.retries` times for each RPC query. This doesn't seem to submit `this.retries` queries but does result in a lot of unnecessary promise reassignment, which _might_ (speculation) be wasting CPU and RAM in a tight loop.
The structure of the change here is made in anticipation of a follow-up commit to introduce some intelligence into the retry loop to avoid retries when the failure was actually "legitimate" (i.e. eth_call revert). Without this change it was proving very difficult to bail out of the retry loop due to the promise chaining that implies the use of closures.
=> fix(RetryProvider): Avoid unnecessary promise reassignment

package.json, src/clients/BundleDataClient/BundleDataClient.ts
Certain chains (currently AlephZero) have a special Block0 timestamp at Unix timestamp 0. To account for this, we should relax the block[0].timestamp > 0 constraint only for block 0.
https://evm-explorer.alephzero.org/block/0
https://evm-explorer.alephzero.org/block/1
=> improve: relax >0 timestamp constraint

src/priceClient/adapters/default.ts, src/priceClient/adapters/index.ts, src/priceClient/priceClient.ts
This adapter can be instantiated by the caller to permit the PriceClient to default to a price of 0 for any token that it was unable to resolve via the preceding adapters. It can additionally be automatically instantiated by the PriceClient based on an input option being set. This therefore provides the caller with a simple way of controlling whether a token price resolution failure should throw or not. It additionally provides a pathway for the caller to be able to specify fixed prices for one or more tokens.
=> improve(PriceClient): Add default price adapter

src/utils/Multicall.ts
This removes a step for deploying to a new OP stack chain.
=> improve(Multicall): Inherit OP stack predeploy

package.json, src/utils/Profiler.ts
Currently this profiler does not accept a logger that doesn't exactly implement Winston's Logger interface, blocking us from using it in the API/frontend.
This allows any logger that has `warn` and `debug` methods.
=> Widen logger type for profiler

package.json, src/providers/retryProvider.ts
Don't adjust the pollingInterval on mainnet because the relatively high block times will result in a lot of unnecessary calls. Additionally, remove the log about dropping the pollingInterval because it's quite noisy in production.
=> improve(retryProvider): Fine-tune polling logic

src/providers/retryProvider.ts
In case of a quorum issue, don't try to log the entire response from the mismatched provider. This may be causing the logger to fall over.
This is currently a suspicion and will be confirmed first in production.
=> fix(retryProvider): Don't log entire RPC responses

package.json, src/relayFeeCalculator/chain-queries/baseQuery.ts, src/utils/FormattingUtils.ts, src/utils/common.ts, test/relayFeeCalculator.test.ts
gas price for now is easily computed by dividing tokenGasCosts by nativeGasCost. In the future, we could break this down further into base fee and priority fee but each network has a different computation right now making this a bit trickier, so this is a good first step
=> improve: Add gasPrice to `TransactionCostEstimate` type

src/clients/BundleDataClient/BundleDataClient.ts, src/constants.ts, src/utils/SpokeUtils.ts, src/utils/common.ts
I'm combing through the SDK for any functions that will need to change once this contracts  [PR](https://github.com/across-protocol/contracts/pull/583) is merged and here are some changes:
- Added comments to BundleDataClient
- Export useful constant `MAX_SAFE_DEPOSIT_ID`
- Export useful utility `isUnsafeDepositId()`
- Delete unused functions that wouldn't work post spoke pool upgrade because the `V3RelayData.depositId` type will change to uint256
=> improve(BundleDataClient): Add comment about not running binary search on "unsafe" deposit ID's

package.json, src/providers/retryProvider.ts
The relayer is currently using the pending block to determine the current base fee. This is inherently incompatible with quorum because some chains will typically not return a consistent pending block.
=> improve(retryProvider): Skip quorum on pending blocks

src/utils/Multicall.ts
OP stack entries are not required here because Multicall3 is assumed to be deployed at the standard address.
https://specs.optimism.io/protocol/preinstalls.html#multicall3
=> chore(multicall3): Drop explicit OP stack entries

src/relayFeeCalculator/chain-queries/alephZero.ts, src/relayFeeCalculator/chain-queries/factory.ts, src/relayFeeCalculator/chain-queries/polygon.ts
The constructor calls in AlephZeroQueries and PolygonQueries are not useful since the `getTokenPrice()` class function is the main changed logic from the parent `QueryBase` class. We can reduce LOC in the repo by removing these constructors. Additionally, we should be able to just use the parent `QueryBase`'s `constructor` directly.
This was partially motivated by work on https://github.com/across-protocol/sdk/pull/801 where I had to modify these constructors because the `QueryBase` constructor changed
=> refactor(QueryBase): Remove constructors in derived classes 

package.json, src/relayFeeCalculator/chain-queries/baseQuery.ts
If we divide `tokenGasCost / nativeGasCost` then we'll get the L1GasCost + L2GasPrice components for the gas price for OpStack, because OpStack adds this L1GasCost component to the full total gas cost.
The SDK should return the `gasPrice = baseFee + priorityFee` to help with debugging against the API, for example against this PR https://github.com/across-protocol/frontend/pull/1335
=> fix(RelayFeeCalculator): Return maxFeePerGas rather than tokenGasCost / nativeGasCost

package.json, src/gasPriceOracle/adapters/arbitrum.ts, src/gasPriceOracle/adapters/ethereum.ts, src/gasPriceOracle/adapters/linea-viem.ts, src/gasPriceOracle/adapters/linea.ts, src/gasPriceOracle/adapters/polygon.ts, src/gasPriceOracle/oracle.ts, test/GasPriceOracle.test.ts
This acts similarly to the baseFeeMultiplier. It is unused for `legacy()` pricing which returns a single gas price so we use the `baseFeeMultiplier` to scale the gas price. It's also unused for the Linea and Arbitrum adapters which only have one component of the gas price that is variable (the priority fee and base fee, respectively) and we use the `baseFeeMultiplier` in both cases.
=> feat(GasPriceOracle): Allow caller to set a priority fee multiplier

package.json, src/relayFeeCalculator/chain-queries/baseQuery.ts, src/relayFeeCalculator/relayFeeCalculator.ts, test/relayFeeCalculator.test.ts
Adds `priorityFeeMultiplier` and `opStackL1GasCostMultiplier` parameters to allow caller to further customize queries
=> improve(RelayFeeCalculator): Add parameters to getGasCosts method

package.json, src/gasPriceOracle/adapters/linea-viem.ts, test/GasPriceOracle.test.ts
I purposefully used the baseFeeMultiplier to multiply the priority fee in Linea because the base fee is fixed, but this caused the relayer to set its scalers incorrectly
=> fix(GasPriceOracle): Use priorityFeeMultiplier in lineaVm adapter

package.json, src/gasPriceOracle/adapters/ethereum.ts, test/GasPriceOracle.test.ts
Can floor the priority fee returned by eth_maxPriorityFeePerGas by using a new environment variable `MIN_PRIORITY_FEE_PER_GAS_`
=> feat(GasPriceAdapter): Allow caller to set a minimum priority fee for eip1559Raw adapter

package.json, src/relayFeeCalculator/chain-queries/baseQuery.ts
Useful for callers to be able to make isolated queries of different parts of the gas fee:
- native gas units
- Op Stack L1 data ee
=> improve(RelayFeeCalc): Add gas cost component getters

package.json, src/clients/BundleDataClient/utils/SuperstructUtils.ts, src/clients/SpokePoolClient.ts, src/clients/mocks/MockSpokePoolClient.ts, src/constants.ts, src/interfaces/SpokePool.ts, src/utils/AddressUtils.ts, src/utils/BigNumberUtils.ts, src/utils/DepositUtils.ts, src/utils/EventUtils.ts, src/utils/SpokeUtils.ts, src/utils/ValidatorUtils.ts, test/SpokePoolClient.ValidateFill.ts, test/utils/utils.ts, test/validatorUtils.test.ts
This should change all instances of `depositId` from a `number` type to a `BigNumber` type. This is done in anticipation of `depositIds` becoming `uint256`s. 
Also, this adds some (currently unused) utility functions to be used in follow-up PRs.
=> improve: interpret depositIds as BigNumbers

src/clients/BundleDataClient/BundleDataClient.ts
This refactor will support additional validation in https://github.com/across-protocol/sdk/pull/842 on the relayer address. If we want to change the refund address for any reason, like we do with the repayment chain today, then we should change it upstream before calling `updateBundleFillsV3`. This makes `updateBundleFillsV3` more of a simple pass-through logic that doesn't implicitly set who gets the refund.
=> improve(BundleDataClient): Add repaymentAddress to updateBundleFillsV3()

package.json, src/clients/BundleDataClient/BundleDataClient.ts
Currently there is a small chance that a fill deadline can fall between block ranges
inspired by @bmzig 's comment here https://github.com/across-protocol/sdk/pull/835#discussion_r1934742099
=> fix(BundleDataClient): Make sure bundle block timestamps have no gaps

package.json, src/clients/BundleDataClient/BundleDataClient.ts, src/clients/BundleDataClient/utils/DataworkerUtils.ts
If a fill cannot be repaid due to `relayerAddress` or `repaymentChainId` being invalid, it still cannot be filled on-chain and therefore has potential to create an unexecutable slow fill.
We currently are early exiting if the fill cannot be repaid and that means a filler could grief the system with invalid repayment info and getting slow fill funds stuck on the destination chain. This could be remedied via admin action but its undesirable.
=> fix(BundleDataClient): If fill cannot be repaid, still account for unexecutable slow fills

src/utils/SpokeUtils.ts
Promoting address (bytes20) -> bytes32 and uint32 -> uint256 still produces the same RelayData hashes. This is verified by the existing tests passing (they are verified against the existing SpokePool deployments with address and uint32 in RelayData).
=> feat: Forwards-compatible getRelayDataHash()

package.json, src/clients/mocks/MockSpokePoolClient.ts, src/utils/AddressUtils.ts, src/utils/EventUtils.ts, test/SpokePoolClient.v3Events.ts
For now, select input fields on events should be automatically truncated to bytes20 evm addresses. This is so that all clients which use the spoke pool client to get deposit/relay/etc. information do not need to handle bytes32 addresses.
Draft until unit tests are made
=> feat: truncate select bytes32 values in events to bytes20 addresses

package.json, src/utils/EventUtils.ts, test/SpokePoolClient.v3Events.ts
While right now, we know that spoke pool events will only emit bytes20 addresses, once the contracts are upgraded, anybody can supply bytes32 addresses to deposit/fill/speedups/etc. functions. This means we should not force these addresses to be bytes20.
=> improve: do not force address coercion for spoke events

package.json, src/clients/BundleDataClient/BundleDataClient.ts, src/clients/BundleDataClient/utils/FillUtils.ts, src/clients/SpokePoolClient.ts, src/clients/mocks/MockSpokePoolClient.ts, src/constants.ts, src/utils/DepositUtils.ts, src/utils/SpokeUtils.ts, test/SpokePoolClient.SpeedUp.ts, test/SpokePoolClient.ValidateFill.ts
- "pre-fill": any fill that is in a bundle that precedes the bundle containing the matched deposit
- "pre-slow-fill-request": a mouthful, and any slow fill request in a bundle that precedes the bundle containing the matched deposit
- "duplicate deposit": a deposit with the same relay hash as an existing one
Evaluate all deposits in the current bundle that were not filled in the current bundle. Figure out whether the deposit was filled, by either:
- Finding the fill in the spoke pool client's memory, or
- Querying the fill status on-chain
If there is a fill for this deposit then we need to issue a refund for this fill because the fill occurred in a previous bundle where it might not have been refunded.
We need to use a similar algorithm for creating slow fill leaves for …
=> feat(BundleDataClient): Support refunds for pre-fills/slow-fill-requests and duplicate deposits

package.json, src/clients/SpokePoolClient.ts, test/SpokePoolClient.v3Events.ts
This is needed so that we can find duplicate fills (i.e. fills with different relay data but with the same deposit ID). E.g. we need to have collisions here so that we can determine invalid fills https://github.com/across-protocol/sdk/blob/2a10e145d028f9c3c6f47ed0c65fc16256c5aa42/src/clients/SpokePoolClient.ts#L384
=> fix: allow collisions for deposit to fill mapping

src/clients/mocks/MockSpokePoolClient.ts, test/SpokePoolClient.v3Events.ts
This change fixes an issue in the way the MockSpokePoolClient produces FilledRelay events. It incorrectly bundles the deposit message field into the fill. When combined with a separate (already fixed) issue in the SpokePoolClient that was unintentionally overwriting the FilledRelay messageHash field based on the message field, this meant that the messageHash was unintentionally _correctly_ recomputed in test, but not in production.
=> fix(test): Correct testing of FilledRelay messageHash

package.json, src/clients/SpokePoolClient.ts
To clean up leftover finalizations from before the upgrade where this event signature changed
=> hotfix(SpokePoolClient): Temporarily query legacy TokensBridged event signature

package.json, src/clients/BundleDataClient/BundleDataClient.ts
If a slow fill request matched with a deposit in a future bundle, then no slow fill leaf is created in that bundle. Instead, the slow fill leaf is created when the deposit is included in the next bundle.
Therefore, if a fast-fill replaces that slow fill request in the same bundle as the deposit triggering the slow fill request, then there is no unexecutable slow fill to be created!
I found this bug while examining prior bundle data trying to figure out why Arbitrum has a persistent small deficit. I narrowed it down to this [slow fill request](https://arbiscan.io/tx/0xa87d13f5cf4aab3e69c35aa335781bf0980374eadf37e2d507b8116362a687e1) for [this deposit](https://explorer.zksync.io/tx/0x7ce35f8d82959a9469c058a1b4f7596d518547d9643fc8b6bac3aa844fa39a5f) that was replaced by this [fast …
=> fix(BundleDataClient): Do not create unexecutable slow fills for pre-slow-fill requests

src/clients/BundleDataClient/BundleDataClient.ts, src/constants.ts
Can merge this in to reduce code once we have confidence that the version 5 bundle data client works well and we won't need to look up any version <= 4 bundles again. If we wanted to do the latter, we could just checkout old code
=> improve(BundleDataClient): Remove conditional canRefundPrefills

package.json, src/clients/BundleDataClient/BundleDataClient.ts, src/clients/HubPoolClient.ts, src/clients/SpokePoolClient.ts, src/utils/EventUtils.ts
To be paired with https://github.com/across-protocol/relayer/pull/2085 in order to speed up relayer marginally when pending bundle data is not yet available on Arweave. Also adds safety checks to BundleDataClient in case there are duplicate events
=> improve(BundleDataClient,SpokePoolClient): Log about duplicate events and delete `getLatestProposedBundleData`

package.json, src/clients/SpokePoolClient.ts, test/SpokePoolClient.v3Events.ts
To store slow fill requests, the indexer needs to retrieve the relevant events from the SDK within the specified block range.
=> feat(spokePoolClient): add getter for slow fill requests

package.json, src/providers/retryProvider.ts
There's no point retrying a transaction with nonce-too-low, so just fail immediately. This mirrors the strategy with transaction simulation failures.
=> improve(retryProvider): Short-circuit on nonce errors

package.json, src/providers/cachedProvider.ts
This [line](https://github.com/across-protocol/sdk/blob/80e2ab26b9dc68265d8d1707a3ee025e03cbc4dc/src/providers/cachedProvider.ts#L77) is triggering and throwing an error when an RPC request for a method like `eth_getTransactionReceipt` has an initial cache type of `DECIDE_TTL_POST_SEND` and then the RPC response reveals a `blockNumber` that is too close to HEAD.
So the `cacheTypeForBlock` is returning `NONE` [here](https://github.com/across-protocol/sdk/blob/80e2ab26b9dc68265d8d1707a3ee025e03cbc4dc/src/providers/cachedProvider.ts#L174) which then throws an error when we try to set this RPC result in the cache
=> fix(CacheProvider): Exit early if cacheType based on blockNumber of RPC response is NONE

package.json, src/clients/SpokePoolClient.ts
The fast relayer logs invalid fills on every SpokePoolCLient update. This is hugely spammy when the relayer loops quickly.
=> improve(SpokePoolClient): Suppress duplicate invalid fill logs

package.json, src/utils/NetworkUtils.ts, yarn.lock
This PR:
- Updates the constants package.
- Modifies the `chainIsEvm` implementation, which used to return always true.
- Adds a new utility function `chainIsSvm`.
=> feat(NetworkUtils): add chainIsSvm helper function

package.json
SDK installation was failing since the scripts folder was not included in the published version.
I've tested this change with a beta version published and it is working now.
```
Error: Cannot find module '.../Across/relayer-v3/node_modules/@across-protocol/sdk/scripts/build-bigint-buffer.js'
at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
at Module._load (node:internal/modules/cjs/loader:1051:27)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:173:12)
at node:internal/main/run_main_module:28:49 {
code: 'MODULE_NOT_FOUND',
requireStack: []
```
=> fix(postinstall): include scripts folder in published version

src/providers/solana/cachedRpcFactory.ts, test/SolanaCachedProvider.ts, test/mocks/MockSolanaRpcFactory.ts
This adds error handling in the cached Solana RPC transport. Specifically, now it does not cache and pass through json-rpc response to rpc client if:
- `getTransaction` underlying transport returns JSON-RPC error response
- `getSignatureStatuses` RPC client request errors
=> fix(svm): handle errors in cached solana provider

package.json, src/utils/Multicall.ts, src/utils/SpokeUtils.ts
This unfortunately doesn't work as intended on Arbitrum One & Orbit chains. These chains unfortunately return the approximate block number of the _underlying_ chain. This is totally jarring and can only be fixed with a custom Multicall3 adaptation for Arbitrum chains.
Maybe one day we'll use blockAndAggregate with a custom Multicall3 deployment on Arbitrum chains. For now, revert to something that works as expected.
=> fix(findDepositBlock): Drop blockAndAggregate

package.json
I believe the most recent release happened out of order which caused the published package to not include any of the new constants, so we need to re-publish the sdk.
=> chore: republish to npm

src/clients/SpokePoolClient.ts
SpokePoolClient.getExecutedRefundLeafL2Token() is no longer required because the OVM SpokePool does not use the legacy ETH address of 0xDeadDeAddeAddEAddeadDEaDDEAdDeaDDeAD0000 anymore. This has probably been redundant since Across v2.5 or v3.
=> refactor(SpokePoolClient): Drop redundant token address substitution

src/utils/CachingUtils.ts, src/utils/DepositUtils.ts, src/utils/SpokeUtils.ts
These function operates solely on a high-level objects (i.e. RelayData + messageHash) and there is no chain-specific implementation. Relocate them to DepositUtils because SpokeUtils will become chain-specific.
=> refactor(SpokeUtils): Relocate chain-agnostic functions

src/clients/BundleDataClient/BundleDataClient.ts, src/clients/SpokePoolClient.ts
SpokePoolClient.getTimeAt() does the same.
=> refactor(SpokePoolClient): Squash redundant block-to-timestamp function

package.json, yarn.lock
It seems like we were missing WETH definitions for Lens in the constants version the SDK is using.
=> chore: bump Across constants

package.json, src/clients/SpokePoolClient.ts, src/utils/SpokeUtils.ts
These are 1:1 in production but some quirks in test are causing failures.
=> fix(SpokePoolClient): Use chain time instead of SpokePool time

package.json, src/clients/BundleDataClient/BundleDataClient.ts, src/clients/SpokePoolClient.ts, src/utils/SpokeUtils.ts
Relayer test has some unfortunate dependencies on _both_ implementations. Back these changes out for now in order to unblock changes in the relayer; we will revisit this.
This reverts commits:
- 4447626182dc381297bab36d4efe2c77be569dcf
- 43965c7ca453787ab528633643c22fcd563ac853
=> fix(SpokePoolClient): Revert to two block-to-timestamp methods

src/clients/BundleDataClient/BundleDataClient.ts, src/clients/SpokePoolClient/EVMSpokePoolClient.ts, src/clients/SpokePoolClient/SpokePoolClient.ts, src/clients/SpokePoolClient/index.ts, src/clients/index.ts, src/clients/mocks/MockSpokePoolClient.ts, test/SpokePoolClient.DepositRoutes.ts, test/SpokePoolClient.SpeedUp.ts, test/SpokePoolClient.ValidateFill.ts, test/SpokePoolClient.fills.ts, test/fixtures/HubPool.Fixture.ts
This change breaks the SDK's SpokePoolClient into specific chains while maintaining the general abstraction that the relayer/indexer/FE has been coded around.
=> feat: refactor for eventual SVM support

src/arch/evm/index.ts, src/arch/index.ts, src/arch/svm/index.ts
The ambition here is for any chain-specific implementations to reside under src/arch/<arch>. This would include basic functionalities like utilities to retrieve blocks, scrape events, perform historical queries, as well as low-level chain-specific SpokePool functions.
This commit only establishes the structure; follow-on work will start populating it.
=> feat: Establish platform-specific code structure

src/clients/HubPoolClient.ts
This recent change https://github.com/across-protocol/sdk/pull/953 removes the pool rebalance routes for a given token when they are reset to the zero address. On its own, this is good, but it mistakenly removes the _entire_ mapping (i.e. it also removes all _historical_ pool rebalance routes for that token). This fixes that issue by only appending a pool rebalance route to `this.l1TokensToDestinationTokens*` if it was set to something other than the zero address.
=> fix: do not delete historical pool rebalance routes

package.json, src/clients/BundleDataClient/BundleDataClient.ts, src/clients/SpokePoolClient/EVMSpokePoolClient.ts, src/clients/SpokePoolClient/SpokePoolClient.ts, src/index.ts
The destinationChainId is implied by the SpokePool being queried, so
remove it as an argument.
While here, add `fillStatusArray` to the set of abstract methods
required by the SpokePoolClient. This is useful down in the relayer.
=> improve(SpokePoolClient): Remove redundant relayFillStatus argument

src/arch/svm/SpokeUtils.ts, src/arch/svm/eventsClient.ts, src/arch/svm/utils.ts, src/clients/SpokePoolClient/SVMSpokePoolClient.ts, test/SpokeUtils.ts
This PR implements the utility function for getting svm fill deadline buffer. That's done by fetching the Spoke Pool's State PDA.
=> feat(svmSpokeUtils): get fill deadline buffer implementation

src/arch/svm/eventsClient.ts, src/arch/svm/types.ts, src/arch/svm/utils.ts, src/clients/SpokePoolClient/SVMSpokePoolClient.ts
The events client basically serves as an SVM `paginatedEventQuery`, which is sometimes used in the bots (e.g. the rebalancer/finalizer). I would like to generalize this class a bit so that it can be used for contracts beyond just the SvmSpoke.
=> improve: allow SVM events client to take in non-spoke IDLs

src/arch/svm/eventsClient.ts
This PR adds support for querying events associated with PDAs in the SvmCpiEventsClient. 
When querying events from a PDA, there are two considerations:
1. The event authority is still derived from the program address, not from the PDA.
2. While we query transaction history by the PDA address, we still need to filter the events that were executed by the program address.
To support this, this PR:
- Adds an optional `pda` parameter to `createFor` method
- Introduces a `queryDerivedAddressEvents` method to specifically query PDA events
- Modifies event filtering logic to handle both program and PDA-specific queries
=> improve(svmEventsClient): enable pda events querying

src/utils/EventUtils.ts
logIndex is unique per block, so there's no need to consider transactionIndex when sorting.
=> refactor(EventUtils): Skip transactionIndex check in event sorting

src/utils/EventUtils.ts
Only blockNumber and logIndex are needed for sorting, so don't require the other fields.
=> improve(EventUtils): Refine sorting types

package.json, src/clients/HubPoolClient.ts
This is a shortcut we can make because in practice, lp fees are 0 for all routes where paymentChain == originChain
=> improve(HubPoolClient): Avoid loading rate model if paymentChain == originChain

package.json, src/clients/BundleDataClient/utils/DataworkerUtils.ts
Bundle deposits (not expired ones) should not create empty pool rebalance leaves because they do not create any RelayerRefundLeaves
=> fix(DataworkerUtils): Don't create empty PoolRebalanceLeaf for bundle deposits

src/utils/SpokeUtils.ts
The Viem ABI encoder permits supplying the ABI as an object, which is faster than ethers, which apparently requires that the ABI be supplied to AbiCoder.encode() as a string. This implies re-parsing the same ABI on each call.
Brief testing showed that the new implementation is 50% faster than the existing one. Producing 500 RelayData hashes locally with takes ~0.5 seconds with viem and ~1 second with ethers. This is relevant in the relayer because performs bulk fillStatus queries of up to 250 RelayData hashes per chain on update, and it has a loop time in the order of low-digit seconds.
=> improve(SpokeUtils): Use viem for RelayData hash computation

src/arch/evm/SpokeUtils.ts, src/arch/svm/SpokeUtils.ts, src/arch/svm/eventsClient.ts, src/arch/svm/utils.ts, src/clients/SpokePoolClient/EVMSpokePoolClient.ts, src/clients/SpokePoolClient/SVMSpokePoolClient.ts, src/clients/SpokePoolClient/SpokePoolClient.ts, src/utils/SpokeUtils.ts
This PR introduces the SVM implementation of `relayFillStatus`, which resolves a relay's fill status using PDA data or, if necessary, PDA events.
The resolution process is:
1. Retrieve the fill status PDA for the relay.
2. If querying the current slot:
- If the PDA exists, fetch the status directly.
- If the PDA doesn't exist but the fill deadline hasn’t passed, solve the status as Unfilled. This relies on the fact that PDAs can't be closed before the fill deadline.
3. If the status can't be determined using the PDA, or if a specific slot is requested, fetch and sort relevant PDA events (fills and slow fill requests) to resolve it.
This PR also introduces `fillStatusArray`, a batched version of the same logic for resolving multiple deposits. Note that resolving status via events for large …
=> feat(SvmSpokePoolClient): relayFillStatus and fillStatusArray implementation

src/arch/svm/SpokeUtils.ts, src/arch/svm/eventsClient.ts, src/arch/svm/types.ts, src/arch/svm/utils.ts, src/clients/SpokePoolClient/SVMSpokePoolClient.ts, test/mocks/MockSolanaEventClient.ts
Just a minor clean up reusing the SVMProvider type we have.
=> chore: reuse SVMProvider type

src/arch/svm/SpokeUtils.ts, src/clients/SpokePoolClient/SVMSpokePoolClient.ts
This PR changes the implementation of `getTimestampForSlot` to use [getBlockTime](https://solana.com/docs/rpc/http/getblocktime). This RPC method does exactly what we need. It takes a slot (despite its misleading name 😅) and returns its timestamp. By using it we no longer need to handle the case when there was no block mined in the requested slot.
This PR also implements `getTimeAt` which also uses `getTimestampForSlot`.
=> improve: SVM getTimestampForSlot

src/arch/evm/BlockUtils.ts, src/arch/evm/index.ts, src/clients/HubPoolClient.ts, src/utils/BlockFinder.ts, src/utils/BlockUtils.ts, src/utils/index.ts
This is the first part of a two-part PR which will adapter the block finder to work for both EVM and SVM. The strategy I am going for is to have a base interface and then passing in generic types to resolve EVM/SVM block types for each block finder.
=> improve: generalize block finder interface for EVM

src/arch/svm/eventsClient.ts
@solana/kit doesn't actually default export anything, only named. this can cause issues in the bundler that consumes this code. 
use named imports only
=> use named imports only for solana/kit

src/gasPriceOracle/types.ts
Prompted by linking against the relayer and seeing a few type incompatibility errors.
=> improve(gasPriceOracle): Add basic gas price type discriminators

src/clients/BundleDataClient/BundleDataClient.ts, src/clients/SpokePoolClient/EVMSpokePoolClient.ts, src/clients/SpokePoolClient/SVMSpokePoolClient.ts, src/clients/SpokePoolClient/SpokePoolClient.ts, src/clients/SpokePoolClient/index.ts, src/clients/index.ts, src/clients/mocks/MockSvmSpokePoolClient.ts, test/SVMSpokePoolClient.fills.ts
We make a lot of assumptions about the structure of the spoke pool client in the relayer. The SVMSpokePoolClient and EVMSpokePoolClient both extend SpokePoolClient but largely do not share a similar API (mainly due to the latter's extensive use of the `spokePool` contract). We can refactor some of this by simply storing the address as a state variable in the SpokePoolClient's class.
=> improve: factor out addresses in spoke pool client

package.json, src/arch/svm/BlockUtils.ts, src/arch/svm/index.ts, src/utils/BlockFinder.ts
Basically a clone of the EVM Block finder in implementation, but the notable thing about this is **this block finder returns blocks, not slots**. This is because the information of a block, such as its number, timestamp, and hash, are not all available when we just return a slot. It should be assumed that everything in this block finder relates to blocks and not slots.
=> feat: SVM BlockFinder 

package.json, src/arch/svm/BlockUtils.ts, src/arch/svm/eventsClient.ts, src/clients/index.ts
We will likely need to expose more spoke pool client functions/variables to support the relayer.
=> improve: expose more spoke pool client objects

src/gasPriceOracle/adapters/solana.ts, src/gasPriceOracle/oracle.ts, src/gasPriceOracle/types.ts, src/providers/utils.ts, src/utils/TypeGuards.ts
Prompted by linking against the relayer and seeing a few type incompatibility errors.
=> improve(gasPriceOracle): Add basic gas price type discriminators (#1031)

package.json, src/arch/svm/eventsClient.ts, src/clients/SpokePoolClient/SVMSpokePoolClient.ts, src/clients/SpokePoolClient/SpokePoolClient.ts
The "enhanced" listener classes down in the relayer need to deal with extending both the EVM and SVM SpokePoolClient variants. This is working well with Typescript mixins, which enable a single class to extend some generic description of a class, but there are a couple of hurdles.
Primarily, the SpokePoolClient depositHashes member is protected, but protected members cannot be declared in the mixin type specification because they are inherently internal. Make depositHashes globally readable for the time being.
Additionally, the SVMSpokePoolClient create static method cannot be used with mixins because it narrows the returned type to an SVMSPokePoolClient. Therefore, remove the protected constraint on the constructor and instead just recommend users to use the create() method.
Ultimately, …
=> chore(SpokePoolClient): Tweaks for downstream implementation

src/arch/evm/SpokeUtils.ts
This requires the caller to verify that they are supplying an EVM-instantiated address to the fill function.
=> chore: Require EvmAddress types on EVM-destination fills

package.json, src/clients/SpokePoolClient/SpokePoolClient.ts
When a large number of these are emitted it blows up the Slack log transports and generally causes performance degradations.
=> chore: Permit suppression of invalid fill warnings

src/utils/AddressUtils.ts, test/AddressUtils.ts
rawAddress is already typed as a Uint8Array so there's no need to revert
to its base16 representation unless it's actually invalid.
For EVM addresses, ensure length is 20 or 32 bytes and require 12 bytes
of padding when the input length is 32 bytes.
For SVM addresses, ensure length is exactly 32 bytes.
=> improve(Address): Tighten & simplify EVM/SVM address validation

src/relayFeeCalculator/chain-queries/baseQuery.ts, src/relayFeeCalculator/chain-queries/svmQuery.ts
Not needed since G's change to overload the gasPriceOracle function prototypes.
=> chore: Drop unnecessary gasPriceOracle typecast

package.json, src/arch/evm/SpokeUtils.ts, src/arch/svm/SpokeUtils.ts, src/interfaces/SpokePool.ts, src/relayFeeCalculator/chain-queries/baseQuery.ts, src/relayFeeCalculator/chain-queries/factory.ts, src/relayFeeCalculator/chain-queries/svmQuery.ts, src/relayFeeCalculator/relayFeeCalculator.ts
- Don't require exclusiveRelayer to be valid on the destination chain,
there's no requirement for this to be true.
- Refocus on RelayData as the core type for "proto" fill types, and 
add supplemental fields as required. This is cleaner.
- Slight re-org in the SpokePool interfaces to permit reuse of some
SpeedUp fields. There's more work to be done to clean this up, but 
hat's deferred for now because it's unrelated to SVM work.
=> improve: Cleanup chain-specific address type handling

package.json, src/arch/svm/SpokeUtils.ts, src/arch/svm/utils.ts, src/clients/mocks/MockSvmCpiEventsClient.ts, src/relayFeeCalculator/chain-queries/svmQuery.ts, test/SVMSpokePoolClient.fills.ts, test/Solana.SvmCpiEventsClient.Integration.test.ts, test/utils/svm/utils.ts, yarn.lock
Summary
This PR updates the SDK to use the latest SVM contract version and migrates relevant SVM logic to support u256 (as Uint8Array) for inputAmount and outputAmount.
Changes
- Bumped @across-protocol/contracts version
- Replaced u64 amount handling with u256 (Uint8Array)
- Updated utils, mock clients, and tests accordingly
=> feat(svm): update to latest contracts and refactor SVM functions for u256 amounts

package.json, src/arch/svm/eventsClient.ts, src/arch/svm/utils.ts
Deposits look like:
```
...
inputAmount: BigNumber { _hex: '0x01', _isBigNumber: true },
outputAmount: '0x0000000000000000000000000000000000000000000000000000000000000001',
...
```
`outputAmount` should be a BigNumber.
=> fix: parse outputAmount as a BigNumber in SVMSpokePoolClient

package.json, src/arch/svm/SpokeUtils.ts, src/arch/svm/provider.ts, src/arch/svm/utils.ts, src/clients/SpokePoolClient/SVMSpokePoolClient.ts, src/typeguards/error.ts
Instances of slots without blocks are showing up semi-regularly in the 
bots. There's currently no handling for this, so it can trigger an
alert.
Some considerations for this change:
- It's unclear whether Solana blockTimes will increase monotonically,
since the Solana docs have a confusing explanation of how time is
produced when calling `getBlockTime()`.
- The SVMSpokePoolClient decides to rotate backwards through slots to
find the first available timestamp from a preceding slot where a
block was actually produced. It's unclear whether the 
SVMSpokePoolClient should do this, however this would effectively
match the EVM-side behaviour.
=> improve(SVM): Handle no-block-at-slot madness

src/clients/HubPoolClient.ts, src/clients/SpokePoolClient/SpokePoolClient.ts, src/clients/mocks/MockHubPoolClient.ts, src/utils/ObjectUtils.ts
`assign` lives at the core of some of the important classes. Found a couple of "`Address` object used instead as string key" situations after adding these type checks
=> improve: enforce type correctness when calling `assign`

src/clients/SpokePoolClient/SpokePoolClient.ts
SpeedUp events are only supported for EVM -> EVM, so any other combination can be discarded immediately.
=> improve(SpokePoolClient): Negate non-EVM SpeedUp recipients

src/arch/svm/utils.ts
The pda uses a int seed and not the state pda to be derived.
=> fix: correct root bundle pda derivation

src/gasPriceOracle/adapters/ethereum.ts, src/gasPriceOracle/adapters/solana.ts
This is useful for bots that want to estimate the real gas price but want to submit with a much higher gas price.
To be paired with this relayer PR: https://github.com/across-protocol/relayer/pull/2414
=> feat: Allow gasPriceOracle to skip using MIN_PRIORITY_FEE when estimating gas

package.json, src/arch/svm/SpokeUtils.ts, test/Solana.SvmCctpMessages.ts
As of right now, we can only finalize messages destined to the svm spoke. This lets us pass in a `recipient` field to cctp deposit functions (which we already have when finalizing) so that we can also finalize EOA transfers.
=> feat: pass in recipient to svm cctp finalizations

package.json, src/arch/svm/utils.ts
related to ACX-4258
When decoding event data, the method we use to determine if an object is an instance of PublicKey is to check the constructor name. Possibly due to minifying issues in the frontend, this is no longer reliable.
We can instead call the toStringTag symbol on the object which won't get stripped since it's explicitly defined in the class definition in`@solana/web3.js`
=> check tostring tag on public key instance

src/arch/svm/SpokeUtils.ts, src/arch/svm/utils.ts, test/SpokeUtils.ts
We encode to/from `RelayData` and `SvmSpokeClient.RelayDataInput` quite a bit, so we should standardize the encoding, which consequently shrinks the amount of code.
=> refactor: consolidate RelayData to Solana RelayData conversion

package.json, src/arch/svm/BlockUtils.ts, src/arch/svm/SpokeUtils.ts, src/arch/svm/utils.ts, src/clients/BaseAbstractClient.ts, src/clients/BundleDataClient/BundleDataClient.ts, src/clients/SpokePoolClient/SVMSpokePoolClient.ts, test/SVMSpokePoolClient.fills.ts
The API doesn't have a logger instance available, so don't require a logger.
=> fix: Make logger optional for SVM utilities

e2e/testTimestampForSlot.e2e.ts, package.json, src/providers/solana/cachedRpcFactory.ts, src/providers/solana/retryRpcFactory.ts
I think there are some Solana errors returned by `transportCall()` that don't throw errors, causing us to avoid falling back or retrying on these errors
=> improve(RetrySolanaRpcFactory): Throw on Solana errors that don't throw errors

src/arch/evm/SpokeUtils.ts, src/clients/SpokePoolClient/EVMSpokePoolClient.ts, src/constants.ts
This is required to set the lower bound for some older SpokePool fillStatus binary searches.
=> improve(utils): Define v2.5 upgrade blocks

package.json, src/clients/BundleDataClient/utils/DataworkerUtils.ts
We need to know the pending root bundle's running balance totals, which is only retrievable by recomputing the pending root bundle's pool rebalance root.
=> feat: running balance calculations for optimistic proposals

package.json, src/coingecko/Coingecko.ts
This adds a method to the `Coingecko` client that allows fetching the current price of a token by only specifying the symbol. We intend to use this feature in the Swap API due to the following reasons:
- Higher cache hit rate for long-tail token price lookups because request query params are uniform throughout chains instead of address+chain combinations
- Higher price lookup success rates for long-tail tokens because address+chain combinations sometimes fail whereas using the token symbol succeeds
- Consistent token prices for same asset
=> feat: add method to `Coingecko` for retrieving price via symbol

src/clients/AcrossConfigStoreClient/AcrossConfigStoreClient.ts
Average block times have been available locally for a long time.
=> refactor(ConfigStoreClient): Drop uma/sdk dependency

package.json, src/coingecko/Coingecko.ts
When fetching a Coingecko price by symbol, they are sometimes returned in uppercase... For example `gho`
=> fix: price lookup coingecko by symbol

src/arch/evm/SpokeUtils.ts, src/arch/svm/SpokeUtils.ts, src/clients/SpokePoolClient/EVMSpokePoolClient.ts, src/clients/SpokePoolClient/SVMSpokePoolClient.ts, src/clients/SpokePoolClient/SpokePoolClient.ts, src/utils/SpokeUtils.ts, test/SpokeUtils.ts
This functionality has way more footgun than is desirable, so centralise it as a way of containing the badness, where it can be tested.
This should be updated subseuently with some additional type validation by grasphoper@.
=> refactor: Centralise FundsDeposited/FilledRelay event unpacking

package.json, src/arch/svm/SpokeUtils.ts
The second `simulateAndDecode` in `hasCCTPV1MessageBeenProcessed` also throws errors transiently, so it's probably a good idea to retry on those.
=> improve: basic retry on hasCCTPMessageBeenProcessed

package.json, src/providers/retryProvider.ts, src/providers/utils.ts
- Relocate parseJsonRpcError() for reuse downstream.
- Avoid retries in additional scenarios (gas-related).
=> refactor(providers): Update transaction submission failure handling

src/gasPriceOracle/types.ts
This doesn't help with typing but does give a simple way of distinguishing between type0 and type2 gas price responses.
=> feat(gasPriceOracle): Add basic utils for type0/type2 discrimination

src/utils/FormattingUtils.ts, test/BlockExplorerUtils.test.ts
8 is too few when the first two are occupied by the 0x prefix and there are two .. chars in the middle.
=> improve(FormattingUtils): Default to 12 char shortened strings

package.json, src/relayFeeCalculator/chain-queries/baseQuery.ts, src/relayFeeCalculator/chain-queries/svmQuery.ts, src/relayFeeCalculator/relayFeeCalculator.ts, test/relayFeeCalculator.test.ts
To account for native token cost, like [`value_amount` in SVM Spoke](https://github.com/across-protocol/contracts/blob/f722857a9cd5edefb8fb33c70b2904a8822725e1/programs/svm-spoke/src/utils/message_utils.rs#L15)
We don't rely on TX simulation, but rather rely on contract enforcing the fixed relayer native token spend when passing in the `value_amount` as a part of `AcrossPlusMessage`
=> feat: add `getAuxiliaryNativeTokenCost` to `QueryInterface` 

src/providers/solana/retryRpcFactory.ts, test/SolanaRetryProvider.ts
Retries happen a lot and they are very noisy, we probably don't need these anymore now that we verify the retry logic mostly is doing what its supposed to do
=> improve(solanaProvider): Remove retry debug logs

package.json, src/arch/svm/SpokeUtils.ts
I think we need to be stricter on the return values of `hasCCTPV1MessageBeenProcessed`. It looks like in practice, this function returns a lot of false negatives due to RPC issues like rate-limiting and other `fetch failed` errors and not because of Solana program errors. I argue that handling for the try/catch here should be done downstream.
=> improve: move cctp try/catches downstream

package.json, src/arch/svm/SpokeUtils.ts, src/arch/svm/types.ts, src/arch/svm/utils.ts
In practice, `hasCCTPV1MessageBeenProcessed` doesn't work for any large amount of messages since each call requires 2 separate calls to `getLatestBlockhash` (which subsequently gets us rate-limited). This lets us pass in an optional latest blockhash parameter to `simulateAndDecode` and `hasCCTPV1MessageBeenProcessed` which should significantly reduce the number of rpc queries we use.
=> improve: add optional blockhash argument to some cctp functions
