package.json

Release the package. See: https://www.npmjs.com/package/@across-protocol/sdk-v2

Configure for release

---

package.json
src/pool/bridgePool.ts
src/pool/contracts/hubPool.ts
src/pool/contracts/index.ts
src/pool/index.ts
yarn.lock

The structure of the event data has changed. Now we have to index into an l1token address for each address, vs before each token was an independent pool contract.  Several events have been removed, and a couple have been added.

feat: update event decoding for hubpool contract

---

src/pool/poolClient.e2e.ts
src/pool/poolClient.ts
src/utils.ts

Small tweaks and bugs fixed during integration with FE

fix: various issues during UI integration

---

.github/workflows/publish.yml

CI: Add publish step

---

package.json

This is trying to do our first publish

feat: release

---

package.json

improve: release

---

package.json
src/coingecko/Coingecko.e2e.ts
src/coingecko/Coingecko.ts
src/utils.test.ts
src/utils.ts
yarn.lock

This is essentially a copy of the CG client from the UMA SDK with a built-in retry.

feat: add retryable CG client

---

.eslintrc.js
.husky/pre-commit
package.json
src/coingecko/Coingecko.e2e.ts
src/coingecko/Coingecko.ts
src/index.ts
src/lpFeeCalculator/lpFeeCalculator.test.ts
src/lpFeeCalculator/lpFeeCalculator.ts
src/pool/contracts/hubPool.ts
src/pool/contracts/index.ts
src/pool/poolClient.e2e.ts
src/pool/poolClient.test.ts
src/pool/poolClient.ts
src/relayFeeCalculator/relayFeeCalculator.ts
src/transfers-history/adapters/db/transfers-repository.ts
src/transfers-history/adapters/web3/SpokePoolEventsQuerier.ts
src/transfers-history/client.e2e.ts
src/transfers-history/client.ts
src/transfers-history/services/SpokePoolEventsQueryService.ts
src/utils.test.ts
src/utils.ts
yarn.lock

override tsdx linitng with eslint and rules from protocol linter.

fix: add eslint and settings from protocol

---

src/pool/poolClient.ts

This switches to liquidityUtilizationCurrent

fix: pool projected apy

---

.github/workflows/publish.yml

Fix npm publish

---

.github/workflows/publish.yml

Fix: npm publish execution 

---

package.json

Fix: Update process release

---

package.json
src/transfers-history/adapters/db/transfers-repository.ts
src/transfers-history/client.ts
src/transfers-history/services/SpokePoolEventsQueryService.ts

Signed-off-by: amateima <amatei@umaproject.org>
Fetching blocks info should be done in batches

fix(tx-history): optimise fetching blocks & release

---

.github/workflows/lint.yml
.github/workflows/test.yml

Fix: Update build image version

---

src/relayFeeCalculator/chain-queries/arbitrum.ts
src/relayFeeCalculator/chain-queries/boba.ts
src/relayFeeCalculator/chain-queries/ethereum.ts
src/relayFeeCalculator/chain-queries/optimism.ts
src/relayFeeCalculator/chain-queries/polygon.ts
src/relayFeeCalculator/relayFeeCalculator.test.ts
src/relayFeeCalculator/relayFeeCalculator.ts

This is a temporary solution to test Vercel integration with Datadog. We can switch to a longer term solution like winston logger once this is confirmed to work.

improve(relayerFeeCalculator): Add logging around relayer fee calculations

---

src/relayFeeCalculator/chain-queries/queries.e2e.ts
src/relayFeeCalculator/relayFeeCalculator.ts

Test isn't correctly testing when coingecko api pro key is defined. Does not affect code in prod as logic does work, but e2e test wasn't specifically testing the logic

fix(e2e-tests): Fix false positive queries.e2e.ts test file 

---

src/coingecko/Coingecko.ts
src/coingecko/index.ts
src/index.ts

Both of these types are returned by functions in the Coingecko class.
Ref: ACX-125

improve(coingecko): Export class + extra types

---

src/coingecko/Coingecko.ts

chore(coingecko): Use msToS() internally

---

package.json
yarn.lock

The Coingecko e2e test seems to be dependent on winston.
Ref: ACX-194

fix(Coingecko): Add winston for tests

---

package.json

Bump package version for new release.

chore: bump version 0.1.23

---

package.json

The only change captured here is the Coingecko request bundling
and caching feature.

chore: Bump version to 0.1.25

---

package.json

Includes changes to remove debug logs

chore: Bump to 0.26

---

src/priceClient/adapters/coingecko.ts

Wasn't really working as intended...
The use of Array.every() instead of Array.some() is a decent QoL upgrade
for anyone who has to understand the validation logic...

fix(PriceClient): Fix CoinGecko response validation

---

package.json

Grab the gas price oracle fix.
Can me merged pending this PR: https://github.com/across-protocol/sdk-v2/pull/112

chore: Bump version to 0.1.30

---

src/gasPriceOracle/oracle.e2e.ts

improve(gasPriceOracle): Rename test fee data

---

package.json

Reverts across-protocol/sdk-v2#122

Revert "chore: Bump to 32"

---

src/priceClient/adapters/defiLlama.ts
src/priceClient/adapters/index.ts
src/priceClient/priceClient.e2e.ts

Interestingly, DefiLlama include a "confidence" score to indicate how reliable they consider the price to be. Might be useful.

improve(PriceClient): Add DefiLlama adapter

---

package.json
src/utils.ts

This adds a simple method to find a block with desired lookback such as 2 days. Tested in relayer-v2.

feat(utils): Add a simple function to find a block with desired lookback

---

package.json
yarn.lock

Signed-off-by: nicholaspai <npai.nyc@gmail.com>

chore: Update @across-protocol/contracts-v2 dependency

---

package.json

Capture priceClient improvements.

chore: Bump SDK 0.2.0 -> 0.2.1

---

src/utils.ts

https://github.com/across-protocol/sdk-v2/pull/131 introduced theroetically useful but buggy function in practice. Will need to dig into bug but for now adds comment about suggested alternative func

improve: Add comment about buggy findBlockAtOrOlder utility func

---

src/utils.ts

See https://github.com/UMAprotocol/UMIPs/pull/567 for corresponding UMIP change

feat: export CONFIG_STORE_VERSION

---

package.json

Exposes CONFIG_STORE_VERSION to relayer-v2

feat: New version

---

package.json
src/contracts/acrossConfigStore.e2e.ts
src/contracts/acrossConfigStore.ts
src/pool/poolClient.ts

Origin and Destination chain are new optional params

feat: Add route rate model

---

src/contracts/acrossConfigStore.e2e.ts

improve(contracts): Update acrossConfigStore.e2e test

---

src/priceClient/adapters/acrossApi.ts
src/priceClient/adapters/baseAdapter.ts
src/priceClient/adapters/coingecko.ts
src/priceClient/adapters/defiLlama.ts

Simplifies usage of the base HTTP class in advance of adding support for retries.

improve(PriceClient): Inherit base HTTP adapter args

---

package.json
src/index.ts
src/interfaces/Error.ts
src/interfaces/index.ts
src/typeguards/error.ts
src/typeguards/index.ts

This PR adds the new relayer Error interface into the SDK

feat: add error interface to common interfaces

---

package.json
src/interfaces/UBA.ts

This PR adds new types to the UBA fee calculator interfaces.

feat: add new uba types

---

package.json
src/transfers-history/adapters/web3/SpokePoolEventsQuerier.ts
src/transfers-history/client.ts
src/utils.ts
yarn.lock

This PR aims to bring the SDK in a compilable state with the new spoke pool upgrades added.

feat: verify types are supported with spoke pool upgrade

---

src/interfaces/UBA.test.ts

Broken by the combination of the previous two commits going in at the same time.

fix(UBA): Update types in predicate test

---

src/interfaces/UBA.test.ts

Minor adjustments:
- Message does not appear in RefundRequested, so move it to sampleDeposit and
sampleFill.
- Relocate destinationChainId.

Align UBA test

---

.github/workflows/lint.yml
.github/workflows/test.yml

Update the node available memory for the CI tests.

CI: Update node size

---

package.json
src/UBAFeeCalculator/UBAFeeCalculator.ts
src/UBAFeeCalculator/UBAFeeConfig.ts
src/UBAFeeCalculator/UBAFeeUtility.ts
src/UBAFeeCalculator/index.ts
src/index.ts
src/interfaces/UBA.ts

This PR migrates the UBA Calculator over from the relayer-v2 to the sdk-v2.

feat(UBA): :sparkles: migrate uba calculator to sdk

---

package.json
yarn.lock

Bump contract package to version with SNX support

chore: bump contracts v2.2.2

---

src/clients/SpokePoolClient.ts
src/constants.ts
src/utils/FillUtils.ts
src/utils/LogUtils.ts
src/utils/index.ts

This change brings in the SpokePoolClient from the relayer into the SDK-V2

feat: add spoke pool client to SDK

---

src/clients/AcrossConfigStoreClient.ts

Implementing a change from an offline discussion. "We can remove these hardcoded catches from lines 85-97 now that we have new spoke pools." ~ @nicholaspai

refactor: :fire: remove hardcoded catches for various pools

---

package.json
yarn.lock

I think we somehow got out of sync as part of commit https://github.com/across-protocol/sdk-v2/commit/4d34289f6ae8876a318f8dc94e11b0de216504e3, but I don't understand how that happened.

chore: Sync yarn.lock

---

package.json

Aligns with the current relayer-v2 minimum.

chore(package): Ratchet up minimum node version

---

.github/workflows/publish.yml

Added new environment variables for increase JS build memory for CI jobs

Improve: Increase CI resources

---

src/UBAFeeCalculator/UBAFeeSpokeCalculator.ts

This PR adds the initial concept of the incentive pool into the UBAFeeCalculator

feat: include incentive pools

---

package.json

The changes for this bump are visible in the HubPoolClient and ConfigStoreClient interface, so I'm bumping the minor.

chore: Bump minor 0.6.3 => 0.7.0

---

package.json
src/clients/index.ts
src/clients/mocks/MockEvents.ts
src/clients/mocks/MockHubPoolClient.ts
src/clients/mocks/MockSpokePoolClient.ts
src/clients/mocks/index.ts

Will be removed from relayer-v2 in a follow-up commit.

chore: Migrate mocked {Hub,Spoke}PoolClient from relayer-v2

---

package.json
yarn.lock

This change bumps the across contracts & project version.

chore(UBA): :package: increase package versions

---

src/UBAFeeCalculator/UBAFeeUtility.ts
src/constants.ts

This chaange adds a utility function to the `UBAFeeUtility` file. This simulates calculating the utilization as described by the Across Data team.

feat(UBA): :sparkles: add utilization calculation in the uba utils

---

src/utils/UBAUtils.ts
src/utils/index.ts

Simple utility to make it easy to check whether the UBA model is in effect.

improve(UBA): Add version helper

---

package.json
src/gasPriceOracle/oracle.ts
yarn.lock

Bedrock implements EIP1559 https://community.optimism.io/docs/developers/bedrock/how-is-bedrock-different/#eip-1559

feat(gas-price-oracle): Change Optimism fee model to EIP1559

---

src/clients/UBAClient.ts

Not sure how this was able to previously pass tests.

fix(UBAClient): Correct use of HubPoolClient

---

src/UBAFeeCalculator/UBAFeeCalculator.test.ts
src/UBAFeeCalculator/UBAFeeConfig.ts
src/UBAFeeCalculator/UBAFeeSpokeCalculator.ts
src/UBAFeeCalculator/UBAFeeUtility.ts
src/UBAFeeCalculator/index.ts
src/clients/AcrossConfigStoreClient.ts
src/clients/UBAClient/UBAClientAbstract.ts
src/clients/UBAClient/UBAClientUtilities.ts
src/clients/UBAClient/UBAClientWithManual.ts
src/clients/UBAClient/UBAClientWithRefresh.ts
src/clients/UBAClient/index.ts
src/clients/index.ts
src/lpFeeCalculator/lpFeeCalculator.ts
src/utils/common.ts

improve: perform additional UBA Client calculations

---

src/clients/UBAClient/UBAClientAbstract.ts

This PR follows up https://github.com/across-protocol/sdk-v2/pull/240

improve: resolve comments per @nicholaspai

---

package.json
src/clients/UBAClient/index.ts

chore(UBA): Additional exports

---

package.json
yarn.lock

Contains fixed POOL token addresses

chore: bump contracts-v2 v2.3.3

---

package.json
src/UBAFeeCalculator/UBAFeeCalculator.test.ts
src/UBAFeeCalculator/UBAFeeUtility.ts

This series of tests aims to verify the code correctness of the various UBA-specific calculations. Checked against data provided from @cc7768

test: add test configuration to UBA Client

---

package.json
src/UBAFeeCalculator/UBAFeeUtility.ts

Related to this comment: https://github.com/across-protocol/sdk-v2/pull/257#discussion_r1243801583

improve: correct max_safe_js_int

---

src/clients/UBAClient/UBAClientWithRefresh.ts

We have a child class in relayer-v2 where it's helpful to prototype new
changes before upstreaming to sdk-v2.

improve(UBAClient): Permit inheritance on UBAClientWithRefresh

---

package.json

Will permit relayer-v2 to extend the UBAClient class.

chore: Bump patch level

---

src/clients/UBAClient/UBAClientUtilities.ts
src/clients/UBAClient/index.ts
src/utils/index.ts

improve: Additional exports

---

package.json

improve: bump version to 0.12.3

---

src/clients/UBAClient/UBAClientBase.ts
src/clients/UBAClient/UBAClientTypes.ts
src/clients/UBAClient/UBAClientUtilities.ts

- getUBAFeeConfig should probably be a `sync` method
- expose `getOpeningTokenBalances` utility method
- `getOpeningTokenBalances` is called incorrectly by `UBAClientBase.update` by passing in token symbol instead of address. I simplify this interface and just pass in `l1TokenAddress` instead of the `l2TokenAddress`

fix: Various fixes

---

src/clients/UBAClient/UBAClientBase.ts
src/clients/UBAClient/UBAClientWithRefresh.ts
src/clients/mocks/MockEvents.ts

fix: sync functions shouldn't return Promises

---

package.json
src/clients/UBAClient/index.ts

For example, relayer-v2 will likely need the ModifiedFlows type

improve(UBAClient): Export more types 

---

package.json
src/clients/AcrossConfigStoreClient/AcrossConfigStoreClient.ts

This re-enables the UBA parsing

feat(UBA): :zap: enable uba parsing

---

package.json
src/clients/HubPoolClient.ts
src/clients/UBAClient/UBAClientTypes.ts
src/clients/UBAClient/UBAClientUtilities.ts
src/clients/UBAClient/UBAClientWithRefresh.ts
src/interfaces/SpokePool.ts

For reference, [this PR](https://github.com/across-protocol/contracts-v2/pull/264/files) implemented most of the refund validation features we take advantage of in this PR.

fix(UBAClient): Fix various bugs in refund request validation

---

package.json
src/UBAFeeCalculator/UBAFeeConfig.ts
src/UBAFeeCalculator/UBAFeeSpokeCalculatorAnalog.ts
src/UBAFeeCalculator/UBAFeeTypes.ts
src/clients/AcrossConfigStoreClient/AcrossConfigStoreClient.ts
src/clients/SpokePoolClient.ts
src/clients/UBAClient/UBAClientUtilities.ts

- much easier to read a JSON rather than stringified version
- remove debug log with no information

improve(ConfigStoreClient): Refine logs

---

package.json
yarn.lock

For access to new testnet definitions.

chore: Bump contracts-v2

---

src/clients/UBAClient/UBAClientUtilities.ts

Handles case where there are no validated proposals in memory before a block

fix(updateUBAClient): Add defaults to loading bundle block ranges and opening balances

---

src/clients/UBAClient/UBAClientUtilities.ts

This restores the ability to run on a testnet.

fix: Use configured chain ID list

---

package.json
src/clients/UBAClient/UBAClientUtilities.ts

fix: Fix getValidRefunds filter

---

src/UBAFeeCalculator/UBAFeeConfig.ts
src/constants.ts
src/utils/BundleUtils.ts

Force clients to call this from the ConfigStoreClient instead

feat: Remove CHAIN_ID_LIST_INDICES

---

src/relayFeeCalculator/chain-queries/zksync.ts

This is just copy/paste of the existing Abitrum adapter, with a few addresses swapped.

feat: zkSync adapter for relay fee calculator

---

.husky/pre-commit
package.json
src/utils/BigNumberUtils.test.ts
src/utils/BigNumberUtils.ts
src/utils/BlockExplorerUtils.test.ts
src/utils/BlockExplorerUtils.ts
src/utils/DeploymentUtils.ts
src/utils/FormattingUtils.ts
src/utils/common.test.ts
src/utils/common.ts
src/utils/index.ts

This PR aims to reconcile the changes requested by both @mrice32 and @pxrl in the previous PR (#377).
These changes include:
- https://github.com/across-protocol/sdk-v2/pull/377#discussion_r1302202280
- https://github.com/across-protocol/sdk-v2/pull/377#discussion_r1302212074
- https://github.com/across-protocol/sdk-v2/pull/377#discussion_r1302235530
- https://github.com/across-protocol/sdk-v2/pull/377#discussion_r1302250483
- https://github.com/across-protocol/sdk-v2/pull/377#discussion_r1302251513
- https://github.com/across-protocol/sdk-v2/pull/377#discussion_r1302207317

improve: post refactoring optimizations

---

package.json
src/clients/SpokePoolClient.ts

Base does not resolve raw ethers addresses into WETH

fix: include base and optimism in leaf l2

---

package.json
src/clients/AcrossConfigStoreClient/ConfigStoreParsingUtilities/ConfigStoreParsingUtilities.test.ts
src/clients/UBAClient/UBAClientUtilities.ts
src/clients/UBAClient/UBAClientWithRefresh.ts
src/pool/poolClient.ts
src/priceClient/priceClient.ts
src/transfers-history/adapters/web3/SpokePoolEventsQuerier.ts
src/transfers-history/services/SpokePoolEventsQueryService.ts
src/utils/FlowUtils.ts
src/utils/FormattingUtils.ts
src/utils/common.ts
yarn.lock

The new upgrade to eslint requires new linting

chore: 🚨 linter warnings 

---

src/utils/index.ts

chore: Export NetworkUtils

---

package.json
src/clients/SpokePoolClient.ts

Makes it easier for relayer to abstract this logic and add additional protection about handling deposit.quoteTimestamps

refactor(SpokePoolClient): Refactor logic about early deposits

---

package.json

Some housekeeping in the package.json docs

docs: add homepage to SDK package.json

---

.gitignore
test/BaseClass.isUpdated.ts
test/ConfigStoreClient.ts
test/mocks/MockUBAClient.ts
test/mocks/MockUBAConfig.ts
test/mocks/index.ts

Migrates over ConfigClient tests.

improve: migrate across config tests

---

package.json
yarn.lock

Upgrade contracts-v2 version to update new BAL address

feat: Export updated BAL address

---

src/clients/SpokePoolClient.ts
src/clients/mocks/MockSpokePoolClient.ts
src/utils/SpokeUtils.ts
test/SpokePoolClient.ValidateFill.ts

This PR resolves all failing tests in the SDK refactor.

fix: resolve failing test

---

src/relayFeeCalculator/relayFeeCalculator.ts

improve: remove unneeded await

---

package.json
src/relayFeeCalculator/chain-queries/index.ts

This PR allows the abstract QueryBase to be exported by the SDK.

improve: export base query

---

src/priceClient/README.md
src/transfers-history/README.md
src/transfers-history/services/README.md

chore: fix typos

---

src/utils/TokenUtils.ts

This is a usage pattern that I keep finding myself using, so I'd like to factor it out to the sdk. It's primarily intended for use with the PriceClient, and will be used in relayer-v2.

feat: Utility for resolving token symbols

---

package.json

This runs each of the build pipelines in parallel. On my system, it reduces the build time from ~14 seconds to ~7 seconds.

improve: Build in parallel

---

src/utils/ArrayUtils.ts

Based on a comment from James.

chore: Clarify use of dedupArray()

---

package.json

Forgot to do this on the previous commit :facepalm:

chore: Bump package

---

package.json
yarn.lock

Need that for the new address of DAI on zkSync

chore: bump constants-v2 package

---

package.json
yarn.lock

KMain motivation is to prepare for upcoming Optimism hardfork which updates the fee formulas https://docs.optimism.io/stack/transactions/fees#l1-data-fee
Signed-off-by: nicholaspai <npai.nyc@gmail.com>

chore: Update eth-optimism package

---

src/clients/SpokePoolClient.ts
src/interfaces/SpokePool.ts

Confirmed by Dong-Ha that this is no longer required.

refactor: Remove UBA -Stringified support

---

package.json
src/clients/SpokePoolClient.ts

This log is useful but extremely noisy

feat: use custom slack channel for logging invalid fills

---

src/relayFeeCalculator/chain-queries/base.ts

Add base sepolia to the list of relayer query classes available.

improve(queries): add base sepolia

---

test/utils/utils.ts

These were missed during a recent update.

fix: Correct test utils type definitions

---

package.json
yarn.lock

...in anticipation of a new contracts-v2 beta release.

chore: Bump contracts to latest beta

---

package.json
src/utils/NetworkUtils.ts

This PR fixes bundling the SDK for a browser env

fix: uma/common import path for browser

---

src/utils/SpokeUtils.ts
test/SpokePoolClient.ValidateFill.ts
test/utils/utils.ts

This is an efficient way of determining bulk fill status in a single RPC call. Both the relayer and dataworker currently make these requests per deposit, so this will reduce RPC consumption and latency.

feat: Support querying relay fill status as an array

---

package.json
src/utils/NetworkUtils.ts

This PR adds a function for use in the relayer for determining if a chainId is related to Linea.

feat(network-utils): add check if ChainId is Linea

---

src/clients/HubPoolClient.ts

Small nit I found while looking into the dataworker V3 linear task.

nit(hubpool): use language feature in update()

---

contracts/MockAcrossMessageContract.sol
package.json
src/constants.ts
src/relayFeeCalculator/chain-queries/baseQuery.ts
src/relayFeeCalculator/relayFeeCalculator.ts
src/utils/NetworkUtils.ts
src/utils/common.ts
test/common.test.ts
test/relayFeeCalculator.test.ts
test/utils/utils.ts
yarn.lock

Bumps the contracts to prep for relayer requirements to operate on Linea.

chore(contracts-v2): bump to 2.5.2

---

package.json
yarn.lock

This should fix the USDT on Linea fee issue

chore: bump contracts-v2 v2.5.4

---

test/HubPoolClient.DepositToDestinationToken.ts
test/HubPoolClient.Utilization.ts
test/SpokePoolClient.SpeedUp.ts
test/SpokePoolClient.ValidateFill.ts
test/SpokePoolClient.v3Events.ts
test/utils/SpokePoolUtils.ts

In advance of a large PR that will remove v2 types.

refactor(test): Migrate remaining v2-related tests to v3

---

package.json
src/clients/SpokePoolClient.ts
src/interfaces/SpokePool.ts

This has some breaking changes for the relayer repository so it's marked WIP for now.

refactor: Remove realizedLpFeePct from Deposit type

---

package.json

chore: Revert version bump

---

src/clients/SpokePoolClient.ts

Allow the caller to specify a timeout on SpokePoolClient.update(). The caller can then use `SpokePoolClient.isUpdated` to determine whether the update was successful.

improve(SpokePoolClient): Support update timeout

---

package.json

chore: Revert package bump

---

src/caching/Arweave/ArweaveClient.ts

Adds more error logs around points of failure we may expect from network issues.

improve(arweave): debugging logs

---

package.json
yarn.lock

Bumps to constant-v2 package with fix for WETH on Sepolia

chore: bump constants-v2 v1.0.16

---

package.json
src/utils/NetworkUtils.ts

This will help consolidate repeated code in the finalizer.

feat(network): include chainIs* functions

---

package.json
yarn.lock

Fixes a type in some chain block explorer URLs.

chore: Bump constants-v2

---

package.json
yarn.lock

improve(constants & contracts): bump package dep versions

---

package.json
src/relayFeeCalculator/chain-queries/index.ts
src/relayFeeCalculator/chain-queries/mode.ts
src/utils/BlockUtils.ts
src/utils/NetworkUtils.ts
yarn.lock

The scope of this PR is only Mode Sepolia. Support for Mode mainnet will follow in a separate PR because `SpokePool` and `Adapter` contracts are not deployed yet.

feat: support mode-sepolia

---

package.json
yarn.lock

Bump contracts + constants versions

chore(constants+contracts): bump versions

---

src/clients/AcrossConfigStoreClient/AcrossConfigStoreClient.ts

This PR adds lite chain support. Additional PRs to follow:
1. Add ability to inject lite chain list for testing
2. Improve testing across this client to include chain id list + lite chain list.

feat(lite-chains): add lite chain support

---

package.json
src/gasPriceOracle/adapters/arbitrum.ts
src/gasPriceOracle/adapters/ethereum.ts
src/gasPriceOracle/adapters/index.ts
src/gasPriceOracle/adapters/linea.ts
src/gasPriceOracle/adapters/polygon.ts
src/gasPriceOracle/oracle.ts

- Minor refactorings & simplifications.
- Tighter scoping for adapter exports.
- Remove unnecessary async/await statements.
- Add fallback strategy for OP stack implementations that are not manually defined. This eases new-chain integrations.
While here, establish a placeholder for a custom Linea gas pricing strategy, to be supported once it is made available on mainnet.

improve(gasPriceOracle): Updates & add Linea

---

package.json
src/gasPriceOracle/adapters/linea.ts

Not ready for 1559 pricing yet.

fix(gasPriceOracle): Revert to type 1 pricing for Linea

---

package.json
yarn.lock

chore: Bump contracts

---

package.json
src/constants.ts
src/utils/BlockUtils.ts
src/utils/NetworkUtils.ts
yarn.lock

This should lead to fewer commits required to add new OP stack chains, and can later be extended to other chain stacks.

improve(utils): Inherit OP stack chain properties

---

package.json
yarn.lock

Includes all changes needed for Scroll.

chore: Bump constants & contracts

---

package.json
yarn.lock

chore: bump contracts and constants

---

package.json
src/constants.ts
yarn.lock

feat: constants + contracts bump for zora

---

package.json
src/caching/Arweave/ArweaveClient.ts
test/arweaveClient.ts

We are multiplying arweave balances by 1e12 too much

fix(ArweaveClient): Fix precision issue

---

src/providers/utils.ts

Added originally in #693 but we should focus on just the migration in that PR

improve: further refactoring

---

package.json
src/clients/BundleDataClient/BundleDataClient.ts

See https://github.com/across-protocol/relayer/pull/1792 for details

fix(BundleDataClient): Ignore slow fill requests involving lite chains

---

package.json
src/clients/SpokePoolClient.ts
src/interfaces/SpokePool.ts

We need the transaction details of speed ups for the indexer.

feat(SpokePoolClient): include speed ups tx info

---

package.json
src/providers/retryProvider.ts
src/providers/utils.ts

Changes include:
- Relayer Change: [61ef0bc94390b73b34f8412e2c84cb043d478f10](https://github.com/across-protocol/relayer/commit/61ef0bc94390b73b34f8412e2c84cb043d478f10)
- Relayer Change: [b55f8744d93cb2602cc7692a63e9376958eea8ff](https://github.com/across-protocol/relayer/commit/b55f8744d93cb2602cc7692a63e9376958eea8ff )
- Relayer Change:  [9e7de096a0f8c017165aa274e81962eef889c455 ](https://github.com/across-protocol/relayer/commit/9e7de096a0f8c017165aa274e81962eef889c455 )

improve: update utils provider from the relayer repo

---

src/utils/JSONUtils.ts

This is one prerequisite for trialing ethers v6 and viem in the bots.

improve(JSONUtils): Handle BigInt on JSON stringification

---

src/clients/HubPoolClient.ts
src/clients/SpokePoolClient.ts
src/clients/mocks/MockSpokePoolClient.ts

The SpokePoolClient currently piggybacks on the HubPoolClient's batch LP fee computation in order to optimise resolving quoteTimestamp to a mainnet block number. This was historically necessary prior to the v3 transition, but it's no longer needed now that the LP fee is computed by upper-layer code. Dropping the LP fee computation will reduce RPC queries on update.

improve(SpokePoolClient): Skip unnecessary LP fee computation

---

package.json

chore: bump package 3.2.3

---

package.json

Forgot to bump on the previous PR.

fix: Bump package version

---

src/clients/SpokePoolClient.ts

The removal of oldestTime exposes a test issue in the relayer. The removal itself is fine, but the test logic is tricky to unpick, so back this out for now.
This reverts commit da9b06ed2c783b1b8ba88a9a71da2072d6ba5c90.

Revert "refactor: Remove SpokePoolClient oldestTime lookup (#752)"

---

package.json
yarn.lock

Gets access to AlephZero network

improve: Update across/constants version

---

src/providers/retryProvider.ts

To protect against possible "revert" confusion, ensure that any RPC responses considered for reverts do not include an error code in the range of [-32768, -32100].

improve(RetryProvider): Check failed RPC responses for JSON RPC response code

---

src/clients/SpokePoolClient.ts
test/SpokePoolClient.ValidateFill.ts

This function is a simple passthrough to `getBlockRangeForDepositId` and there is no advantage to having it be a class level function. It was only this way for testing purposes but we can just as easily test the stateless utility function itself.
This PR cleans up the code

refactor(SpokePoolClient): Remove _getBlockRangeForDepositId

---

package.json
src/clients/BundleDataClient/BundleDataClient.ts
src/gasPriceOracle/adapters/ethereum.ts
src/relayFeeCalculator/chain-queries/baseQuery.ts
src/utils/common.ts
test/GasPriceOracle.test.ts

Intuitively, the floor in the eip1559Raw calculation shouldn't be multiplied by the multiplier

improve(GasPriceOracle): Return opStackL1DataFee and floor after scaling priority fee

---

src/clients/BundleDataClient/BundleDataClient.ts
src/utils/SpokeUtils.ts
test/SpokePoolClient.fills.ts

Builds off of the existing `findFillBlock()` function. We'll need this function in the BundleDataClient to create refunds for pre-fills

feat: Add findFillEvent utility function

---

test/SpokePoolClient.v3Events.ts
test/utils/SpokePoolUtils.ts
test/utils/utils.ts

Test utils has a few v2 -> v3 hangovers and some incomplete types. Flush the redundant code and apply some minor cleanup.

fix(test): utils cleanup

---

test/SpokePoolClient.v3Events.ts

This change makes some test adjustments to reduce the diff in a subsequent PR, relating to the introduction of new event types. It also takes advantages of some recent simplifications in the event mocking framework to remove some annoying type assertions.

refactor(test): Test tweaks in advance of pending event changes

---

src/clients/SpokePoolClient.ts

Diff minimisation to reduce the size of the subsequent diff for the pending contract upgrade.

chore(SpokePoolClient): Backport changes

---

package.json
src/utils/SpokeUtils.ts

Changes to functions being used to simulate.

feat: post upgrade changes

---

src/clients/HubPoolClient.ts
src/interfaces/HubPool.ts
test/HubPoolClient.RootBundleEvents.ts
test/utils/HubPoolUtils.ts

Leftover type from UBA work, we should remove

improve: Remove incentiveBalance from type

---

package.json
yarn.lock

Needed for testnet efforts in the relayer.

chore: bump contracts version

---

src/providers/cachedProvider.ts

We can remove a large if-statement indent if we early exit. There is no logical change in this PR

refactor(CacheProvider): Early exit if CacheType == NONE

---

src/lpFeeCalculator/lpFeeCalculator.ts
test/lpFeeCalculator.test.ts

See accompanying UMIP change here: https://github.com/UMAprotocol/UMIPs/pull/614.

feat: cap LP fees at 100%

---

src/clients/HubPoolClient.ts

Driveby change spotted while reviewing @bmzig's Address PR.

improve(HubPoolClient): Remove unnecessary type assertion

---

src/clients/SpokePoolClient.ts

- Drop redundant type declarations.
- Minor code golfing.

refactor(SpokePoolClient): Minor tidy-up

---

src/clients/SpokePoolClient/EVMSpokePoolClient.ts
src/clients/SpokePoolClient/SpokePoolClient.ts

Relevant changes:
* https://github.com/across-protocol/sdk/pull/934#discussion_r2012425447
* https://github.com/across-protocol/sdk/pull/934#discussion_r2012428586
* https://github.com/across-protocol/sdk/pull/934#discussion_r2012429528
Changes not added:
* https://github.com/across-protocol/sdk/pull/934#discussion_r2012422468
* Will wait until this PR is merged to remove this function

improve: add changes recommended by PR review

---

package.json
src/constants.ts
src/relayFeeCalculator/chain-queries/customGasToken.ts

Relay fee calculator fails due to missing GHO mapping.

feat: add lens gho as custom gas token

---

package.json
src/utils/BundleUtils.ts

Same changes here https://github.com/across-protocol/sdk/commit/c53b1830dd1ba7b61a192baca5835062d2a61edc

chore: sync master with alternate release branch

---

package.json
yarn.lock

I think this is the last time.

chore: bump constants

---

src/clients/SpokePoolClient/SVMSpokePoolClient.ts

This PR simply specs out the SVM spoke client - it's not meant to be merged to master and will live in the epic while @melisaguevara and I build out the function specifics

chore: create skeleton for svm spoke client

---

src/clients/BundleDataClient/BundleDataClient.ts
src/clients/BundleDataClient/utils/SuperstructUtils.ts

- Introduced a new function to convert sortable event fields into required fields, ensuring consistent naming conventions.
- Updated the processing of bundle data to utilize this new function for various event arrays, enhancing data integrity.
- Modified the Superstruct schema to accommodate optional transaction fields, improving validation flexibility.

feat: add data normalization for sortable event fields

---

src/clients/HubPoolClient.ts

Follow up to relayer PR https://github.com/across-protocol/relayer/pull/2196

improve: Remove unused functions

---

package.json
src/relayFeeCalculator/relayFeeCalculator.ts

Based gas fees on input token decimals

fix: relay fee calculator gas fee denomination

---

package.json
src/utils/TypeGuards.ts
test/providers.test.ts

checking for svm specific methods for some reason does not work. 
this breaks the gas price oracle

fix isEvmProvider, add test case

---

package.json
src/arch/svm/SpokeUtils.ts
src/arch/svm/utils.ts
src/relayFeeCalculator/chain-queries/svmQuery.ts
src/relayFeeCalculator/relayFeeCalculator.ts
test/SVMSpokePoolClient.fills.ts
test/utils/svm/utils.ts

Changes proposed in this PR:
- Fix Svm gas estimation functions
- Add unit test for `getNativeGasCost` and `getGasCosts`

fix(svm): svm gas queries

---

src/arch/svm/SpokeUtils.ts
src/utils/AddressUtils.ts
tsconfig.json

This helps Typescript compiler catch type mismatch errors

improve: add `__brand..` private var to `Address` variants

---

src/clients/SpokePoolClient/index.ts
src/clients/index.ts

Export SpokePoolManager so it can be used in relayer repo

fix: Export SpokePoolManager

---

src/clients/BundleDataClient/BundleDataClient.ts
src/interfaces/SpokePool.ts
src/utils/DepositUtils.ts

improve: do not log full Address type

---

package.json
src/arch/svm/utils.ts
src/clients/BundleDataClient/BundleDataClient.ts
src/clients/BundleDataClient/utils/PoolRebalanceUtils.ts
yarn.lock

Required by the proposer when selecting a bundle end block range.

feat(svm): Support resolving latest finalized slot with block

---

src/clients/SpokePoolClient/EVMSpokePoolClient.ts
src/clients/SpokePoolClient/SVMSpokePoolClient.ts
src/clients/SpokePoolClient/SpokePoolClient.ts
src/clients/SpokePoolClient/index.ts
src/clients/SpokePoolClient/types.ts

Replace `instanceof` checks for spokePoolClient type

improve: Replace instanceof checks for spokePoolClient type

---

package.json
src/interfaces/CachingMechanism.ts
src/interfaces/PubSubMechanism.ts
src/interfaces/index.ts

https://github.com/across-protocol/relayer/pull/2359

feat: Added del method to caching interface

---

src/priceClient/priceClient.ts

Tested locally:
```
2025-07-16 19:02:43 [debug]: {
"at": "ProfitClient",
"message": "Updated token prices",
"tokenPrices": {
"0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2": "3333870000000000000000",
"0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48": "999872000000000000",
"0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599": "119442000000000000000000",
"0x04Fa0d235C4abf4BcF4787aF4CF447DE572eF828": "1240000000000000000",
"0x6B175474E89094C44Da98b954EedeAC495271d0F": "1000000000000000000",
"0x42bBFa2e77757C645eeaAd1655E0911a7553Efbc": "104128000000000000",
"0x3472A5A71965499acd81997a54BBA8D852C6E53d": "1220000000000000000",
"0xba100000625a3754423978a60c9317c58a424e3D": "1220000000000000000",
"0xdAC17F958D2ee523a2206206994597C13D831ec7": "1000000000000000000",
"0x44108f0223A3C3028F5Fe7AEC7f9bb2E66beF82F": …
```

improve: use case-sensitive strings to request prices from priceFeeds

---

src/clients/SpokePoolClient/SpokePoolClient.ts
test/SpokePoolClient.SpeedUp.ts

The PR to modify SpeedUp handing predated merging the Address class.

fix(test): Fix SpeedUp tests

---

src/utils/TokenUtils.ts
test/SpokePoolClient.v3Events.ts
test/fixtures/HubPool.Fixture.ts
test/utils/SpokePoolUtils.ts
test/utils/utils.ts

Claude pulled some of these out.

fix(test): Misc test type fixes

---

test/relayFeeCalculator.test.ts

Increase fillDeadline time in tests

fix: Increase fillDeadline time in tests

---

package.json
src/clients/BundleDataClient/utils/DataworkerUtils.ts
src/clients/BundleDataClient/utils/FillUtils.ts
src/clients/BundleDataClient/utils/PoolRebalanceUtils.ts
src/clients/HubPoolClient.ts
src/clients/SpokePoolClient/SpokePoolClient.ts
src/clients/mocks/MockHubPoolClient.ts
test/HubPoolClient.DepositToDestinationToken.ts
test/mocks/MockHubPoolClient.ts

Reverts across-protocol/sdk#1197
was reverted to get https://github.com/across-protocol/sdk/pull/1194 in before solana launch

feat(HubPoolClient): Handle disabled pool rebalance routes
